### ISSUE TITLE
Pruebas Novedad de cesión

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/novedades_cliente#1]
Realizar pruebas con fin de verificar y familiarizarse con el funcionamiento del proceso de novedades y su cesión respectiva.

**Comment by anlramirezs11** [comment]
### **Prueba de Cesión**

Se ingresa a la novedad de cesión de contrato número 28 y se realiza una prueba de funcionamiento cediendo el contrato a otra persona.
![1](https://user-images.githubusercontent.com/29903400/59700742-9f5a8e00-91b9-11e9-8111-00809cf297ed.png)

Al clikear el botón “Crear Novedad de Cesión” se genera el pdf: [acta_cesion.pdf](https://github.com/udistrital/novedades_cliente/files/3302424/acta_cesion.pdf)

Al buscar el contrato 28 aparece el siguiente pop-up informado: 
![2](https://user-images.githubusercontent.com/29903400/59701005-3de6ef00-91ba-11e9-953c-30019b44234c.png)

**Comment by BOTOOM** [comment]
ya que las pruebas fueron realizadas se procede a cerrar el issue
