### ISSUE TITLE
verificacion de estructura de pdf para las novedades

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#11]
se requiere verificar la estructura de los pdf generados en el cliente, esto con el fin de actualuzarlos a las ultimas plantillas suministradas.

debido a que las ultimas planillas tienen varios cambios se requiere saber que datos se tienen en común entre las plantillas generadas por el cliente y las suministradas al equipo.

se tiene en cuenta que el cliente y su ambiente de test aun no están en completo funcionamiento por ende en esta tarea también se contemplara el proceso para que el cliente funcione a su mejor manera posible en el ambiente de test.

**aclaracion**

en el issue no se contempla el la actualización de las platillas

**Comment by BrayanB24** [comment]
Se comienza con el desarrollo del ajuste de las plantillas de las novedades.

**Comment by BrayanB24** [comment]
Para poder comenzar a comparar las novedades se necesita que el cliente de novedades_cliente esté funcionando de manera correcta, la primera parte de este issue listará los problemas que tiene el cliente de novedades de preproducción, para comenzar a ser corregidos.

**Comment by BrayanB24** [comment]
Al cargar la página principal de novedades postcontractuales, el campo de vigencia contrato debe consultarse desde el API de administrativa_amazon_api las vigencias de los contratos, al revisar el api sin WSo2 el principal problema y tal vez la causa de este resulta ser que la respuesta obtenida no es formato JSON como lo muestra la imagen a continuación: 

![image](https://user-images.githubusercontent.com/45292226/65339170-4d971a80-db91-11e9-853a-aee37cc59f24.png)

la petición realizada es la siguiente: 
[http://pruebasapi.intranetoas.udistrital.edu.co:8104/v1/vigencia_contrato/?](url)

Por lo que este endpoint debe ser refactorizado y el cliente modificado para utilizar la respuesta.

**Comment by BrayanB24** [comment]
Seguido la función que consulta toda la información relacionada con el contrato al cual se le quiere generar la novedad la cual es [http://jbpm.udistritaloas.edu.co:8280/services/contratoSuscritoProxyService/contrato/49/2018](url) No está pasando por WSo2 y tampoco está respondiendo en formato JSON, al no pasar por WSO2 se está dirigiendo a través de http por lo que el navegador entrega un Mixed Block, por lo que tiene tráfico compartido. Para solucionar este error de API es necesario registrar esta API en WSO2 y corregir el formato de la respuesta a JSON

**Comment by BrayanB24** [comment]
Luego de revisar con el arquitecto el correspondiente servicio de JBPM que consulta los contratos partiendo del numero y la vigencia, se llega a la conclusión de que debe ser cambiada una cabecera de la petición para que el servicio responda en formato JSON además de que el servicio de vigencias debe estar funcionando de manera correcta. 

Por otro lado, el servicio de Administrativa Amazon api está funcionando de manera correcta sin embargo entrega la respuesta en tipo Array como se mostró en un comentario anterior. Se realizarán las pruebas correspondientes.

**Comment by BrayanB24** [comment]
Se superan los problemas presentados con las dos API nombradas anteriormente, se tiene problema ahora con el API Novedades_API cuyo metodo Get y GetAll no se encuentran refactorizados, por lo que se debe proceder con esto antes de poder continuar, lo más probable es que se necesite modificar el cliente también para que pueda obtener los datos del API Refactorizado.

**Comment by BrayanB24** [comment]
Realizado el refactor en el API se procede a hacer las modificaciones del cliente, con el fin de que las modificaciones realizadas sean compatibles.

**Comment by BOTOOM** [comment]
la tarea de devuelve al backlog para dar prioridad a tareas que se requieren para seguir con esta

**Comment by BOTOOM** [comment]
se cierra ya que ya se maneja en los siguientes issues #72 #68 #69
