### ISSUE TITLE
Manual de Usuario de Novedades.

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#12]

**Comment by anlramirezs11** [comment]
Se realiza una actulización del manual de usuario del modulo de novedades: 
https://docs.google.com/document/d/1hiZnK4C-dwIRJ-WgYJhf6te_I_rTK4t6OdxDqPXjfpc/edit?usp=sharing
Queda penciente relizar una actualización en la novedad de Adición y Prorroga ya que mañana (12/11/2019) se relizará una presentación al usuario para definir la lógica de esta novedad.

**Comment by BOTOOM** [comment]
okay apenas este listo el manual pasa el issue a aprobado :smile:

**Comment by anlramirezs11** [comment]
Se actualiza el manual de usuario: https://docs.google.com/document/d/1hiZnK4C-dwIRJ-WgYJhf6te_I_rTK4t6OdxDqPXjfpc/edit?usp=sharing
