### ISSUE TITLE
Apropiación de generalidades del sistema

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/novedades_cliente#128]
https://drive.google.com/drive/u/0/folders/13PKbjlSI-ndcGyIyxUVF_BKoNNYG_WZs

**Comment by JuanCamiloMartinezLopez** [comment]
Se genero un [documento](https://docs.google.com/document/d/1cqzJ6diy-X0LcpneHwQVTF8PjHwDuF2Ijgic69k-9Mo/edit?usp=sharing) a forma de resumen y guía frente al desarrollo de la fase pasada.
