### ISSUE TITLE
Validación de funcionalidades

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/novedades_cliente#130]
Validar las funcionalidades del sistema para su correcto funcionamiento.

- [x] Búsqueda de contrato
- [ ] Corrección de errores en css

Validar la generación de las diferentes actas del sistema y corregir posibles errores

Actas
- [x] Adición y prorroga
- [x] Suspensión
- [x] Reinicio
- [x] Cesión
- [x] Terminación anticipada

**Comment by FrederickUdis** [comment]
se actualizo la librería de iconos como se muestra en la siguiente imagen 

![image](https://user-images.githubusercontent.com/30853509/100122796-cfdf3680-2e47-11eb-82da-2c8f2300c82c.png)

estos soluciona el error al inicio de correr la pagina

**Comment by ddguerra90** [comment]
El acta de cesión presentaba en el pdf invalid Date en la fecha de suscripción
![image](https://user-images.githubusercontent.com/31446845/100132251-24d47a00-2e53-11eb-8df3-33520e855a3c.png)

Se revisa el archivo **acta_cesion.js** correspondiente a la creación de esta acta y se modifican las líneas 596 y 603, cambiando la función **format_date_letter** por **format_date_letter_mongo** solucionando este error en el pdf creado

![image](https://user-images.githubusercontent.com/31446845/100132457-711fba00-2e53-11eb-9721-fc8543dac043.png)

**Comment by FrederickUdis** [comment]
se presenta un error a buscar numeros de actas que no se encuentran en la base de datos.
se corrigió con el uso de excepciones y se implemento una mensaje de alerta como se puede ver en la siguiente imagen

![image](https://user-images.githubusercontent.com/30853509/100382935-6f3c2f00-2fea-11eb-8857-a56e6c5c1193.png)

**Comment by JuanCamiloMartinezLopez** [comment]
### **NOVEDAD ADICIÓN Y PRORROGA**
los siguientes errores se solucionan en el archivo **app/scripts/controllers/seguimientoycontrol/legal/acta_adicion_prorroga.js**
### **Errores en el acta de novedad adición y/o prorroga:** 
**1.  Valores indefinidos:** Al realizar un adicion, pero no una prorroga se mostraba el valor de esta en 'undefined'.
![error_undefined_adicion_y_prorroga](https://user-images.githubusercontent.com/42418412/100396795-7e37d700-3014-11eb-8fee-8daada4820ce.png)
para resolverlo dentro de la función **comprobar_seleccion_novedad**, en la linea 295 se agrega las siguientes lineas:
![codigo_solucion_error_undefined_adicion prorroga](https://user-images.githubusercontent.com/42418412/100397002-8f351800-3015-11eb-8d50-393908738ab3.png)
Por lo que en caso de no hacer una prorroga, el valor mostrado seria:
![solucion_undefined_adicion_y_prorroga](https://user-images.githubusercontent.com/42418412/100397036-bf7cb680-3015-11eb-8826-b9cb152c06c6.png)

**2. Espacios faltantes:** se agregan espacios faltantes para mejor el aspecto del acta.
Ejemplo:
![espacio_faltante_adicion prorroga_1](https://user-images.githubusercontent.com/42418412/100397253-acb6b180-3016-11eb-938b-d7a46d50bea9.png)
### **Errores en la creación del acta de novedad adición y/o prorroga:**
Se agrego la captura y visualización del error al momento de generar el acta.
![mensaje_error_adicion prorroga](https://user-images.githubusercontent.com/42418412/100397670-f3a5a680-3018-11eb-8782-901a283a31b0.png)
este mensaje e intercepcion de los errores se resolvio con el siguiente codigo en la linea 417 en la funcion **generarActa**
![codigo_manejo_errores_adicion prorroga](https://user-images.githubusercontent.com/42418412/100397675-f6080080-3018-11eb-89e2-dd9bb9ab8446.png)

**Comment by JuanCamiloMartinezLopez** [comment]
### **NOVEDAD SUSPENSIÓN**

Se agrega el manejo de errores, junto con la implementación de una alerta sobre esta. esto realizado en el archivo **app/scripts/controllers/seguimientoycontrol/legal/acta_suspension.js**.
![mensaje_error_suspension](https://user-images.githubusercontent.com/42418412/100490574-587d0180-30ea-11eb-9b7c-80dbbcac8f96.png)
mediante el siguiente codigo en la linea 214, en el metodo **generarActa**
![codigo_solucion_suspension](https://user-images.githubusercontent.com/42418412/100490606-8bbf9080-30ea-11eb-85f8-d82b9da43726.png)

**Comment by JuanCamiloMartinezLopez** [comment]
### **NOVEDAD TERMINACIÓN ANTICIPADA**
**1. Fechas invalidas:**
se corrigió el problema de las fechas invalidas en el documento **app/scripts/controllers/seguimientoycontrol/legal/acta_terminacion_liquidacion_bilateral.js** en las lineas 175 en la función **selecionarSaldo**, 650, 664 y 733 en la funcion **generarActa** el cambio de la función **format_date_letter** por **format_date_letter_mongo** mostrada antes en el https://github.com/udistrital/novedades_cliente/issues/130#issuecomment-733137735.

**2. Nombre del documento:**
El documento pdf se generaba con un nombre incorrecto, ejemplo **acta_terminacion_anticipada_7,266.pdf**, debiendo mostrar el numero del contrato, para el caso del ejemplo **acta_terminacion_anticipada_1341.pdf**. Este error se soluciona haciendo el siguiente cambio en la función **formato_generacion_pdf**.
![cambio_nombre_nov_terminacion](https://user-images.githubusercontent.com/42418412/100490947-f0c8b580-30ed-11eb-879c-84057a497cd3.png)
**3. Manejo de errores**
Se agrega el manejo de errores, junto con su respectiva alerta.
![mensaje_error_terminacion](https://user-images.githubusercontent.com/42418412/100491616-012f5f00-30f3-11eb-86d5-b858efebae8e.png)
esto se logra implementando el siguiente código en la linea 250 de la función **generarActa**.
![codigo_manejo_error_terminacion](https://user-images.githubusercontent.com/42418412/100491664-8286f180-30f3-11eb-8308-566cb5f4110b.png)

**Comment by JuanCamiloMartinezLopez** [comment]
### NOVEDAD REINICIO ###

**1. Información contratista** La información del contratista no era traída de forma correcta, por lo que no era mostrada. se resolvió sacando la petición al mid de agoraRequest que se encontraba dentro de la petición al novedadesMidRequest, colocándola antes de esta, esto en el archivo **app\scripts\controllers\seguimientoycontrol\legal\acta_reinicio.js**.
![datosContratistaReinicio](https://user-images.githubusercontent.com/42418412/101363330-44b26780-386f-11eb-8efd-17947ee4720b.png)

**2. Información de la suspensión** Dado que la petición encargada de traer sobre la información de la suspensión realizada no funcionaba de forma correcta, se opto por habilitar dentro de la vista de reinicio habilitar el formulario para que el usuario ingrese estos datos.
Por lo que se agrega el siguiente código en el archivo **app\views\seguimientoycontrol\legal\acta_reinicio.html**.
![formReinicio](https://user-images.githubusercontent.com/42418412/101363985-0b2e2c00-3870-11eb-98a7-f675c6b0fb7e.png)
Junto con los siguientes cambios en el controlador de esta vista,  **app\scripts\controllers\seguimientoycontrol\legal\acta_reinicio.js**.

- **Cambio en las variables**
Se hace este cambio en las variables dentro de todo el controlador
![variables_reinicio](https://user-images.githubusercontent.com/42418412/101364677-d4a4e100-3870-11eb-8413-506620f02143.png)
- **watchers**
se agregan los siguientes watchers para el formulario.
![formReinicio_watchers](https://user-images.githubusercontent.com/42418412/101364831-028a2580-3871-11eb-9dd4-7d0560148817.png)

**Comment by JuanCamiloMartinezLopez** [comment]
### ACTAS DE PRUEBA FINALES ###
A continuación se adjuntan actas de muestra para evidenciar los resultados de los cambios realizados
- [acta_adicion_prorroga_contrato_1336(1).pdf](https://github.com/udistrital/novedades_cliente/files/5655376/acta_adicion_prorroga_contrato_1336.1.pdf)
- [acta_suspension_contrato_1337(1).pdf](https://github.com/udistrital/novedades_cliente/files/5655379/acta_suspension_contrato_1337.1.pdf)
- [acta_reinicio_contrato_1337(1).pdf](https://github.com/udistrital/novedades_cliente/files/5655383/acta_reinicio_contrato_1337.1.pdf)
- [acta_cesion_contrato_1391.pdf](https://github.com/udistrital/novedades_cliente/files/5655384/acta_cesion_contrato_1391.pdf)
- [acta_terminacion_anticipada_1391.pdf](https://github.com/udistrital/novedades_cliente/files/5655388/acta_terminacion_anticipada_1391.pdf)

**Comment by FrederickUdis** [comment]
**Eliminación de la librería**
Se elimino la actualización de la librería por incompatibilidad de con los iconos del menu.
