### ISSUE TITLE
Persistencia de novedades en base de datos

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/novedades_cliente#134]
Solucionar los problemas que impiden la persistencia de la información de las novedades en la base de datos.

**Comment by JuanCamiloMartinezLopez** [comment]
### Base de datos novedades
se encontró el problema por el cual el sistema no estaba registrando la información de las novedades en la **db:udistrital_administrativa**, **schema:novedades**, **tabla:novedades_postcontratuales**.
el novedades_crud nos mostraba el siguiente error al momento de hacer el post de la novedad.
`ERROR: permission denied for sequence novedades_postcontratuales_id_seq`
por lo que mediante la ayuda de los DBA se encontró que se debía a una falta de permisos para el usuario de esta base de datos, y ellos mismos solucionaron el error, como se puede ver en la siguiente imagen.
![prueba_base_de_datos](https://user-images.githubusercontent.com/42418412/102704808-1872ef80-424e-11eb-9845-8ba7f502d329.png)

**Comment by JuanCamiloMartinezLopez** [comment]
### Corrección de valores replicados
El sistema replicaba los siguientes valores.

- Adición y prorroga
![informacion_replicada_adicion6prorroga](https://user-images.githubusercontent.com/42418412/102705256-76ee9c80-4253-11eb-88fa-b5ca50e98b10.png)
- Cesión
![informacion_replicada_cesion](https://user-images.githubusercontent.com/42418412/102705258-80780480-4253-11eb-9880-d19991b89111.png)
se requiere cambiar los siguientes valores:
- Adición y prorroga:
fecha_inicio: null
contratista: null
- Cesion:  
fecha_inicio: null
numero_cdp: null
vigencia_cdp: null
valor_novedad: null


Para esto se realizan los siguiente cambios:
- Adición y prorroga
en el modelo **models/adicionprorroga.go** en la funcion **FormatAdmAmazonNovedadAdProrroga** linea 280 hacemos los siguientes cambios.
![codigo_adipro_replica](https://user-images.githubusercontent.com/42418412/102705365-fe88db00-4254-11eb-8d66-5ea18f7ecc1c.png)
- Cesión
en el modelo **models/cesion.go** en la funcion **FormatAdmAmazonNovedadCesion** linea 592 hacemos los siguientes cambios.
![codigo_ces_replica](https://user-images.githubusercontent.com/42418412/102705397-62ab9f00-4255-11eb-9bc6-01013a800487.png)


quedando de la siguiente forma
- Adición y prorroga
![corregido_adicion_replica](https://user-images.githubusercontent.com/42418412/102705413-8b339900-4255-11eb-8c42-eafcc615c9eb.png)
- Cesión
![corregido_cesion_replica](https://user-images.githubusercontent.com/42418412/102705417-92f33d80-4255-11eb-9d2c-66e9fbfff48e.png)


###Problemas
aunque vemos que la fecha de inicio fue corregida, los valores integer y numeric no muestran el null, aunque se les este enviando.
![objeto_enviado](https://user-images.githubusercontent.com/42418412/102705438-eebdc680-4255-11eb-8b90-e46f983c5404.png)
También vemos que el sistema replica la novedad de adición y prorroga, mas no una novedad de solo adición o prorroga

**Comment by JuanCamiloMartinezLopez** [comment]
### REPLICA EN ARGO
Actualmente se hace un replica de los datos de las novedades Cesión y Adición y Prorroga, esto mediante una solicitud del supervisor con el siguiente artefacto.
![artefacto_supervisor](https://user-images.githubusercontent.com/42418412/103041964-f4f9be80-4545-11eb-8b47-79290d15f7cd.png)
siendo subida la siguiente información a la base de datos
- Cesión
![cesion_actual_argo](https://user-images.githubusercontent.com/42418412/103042422-8cabdc80-4547-11eb-9cfe-1483fa4665c1.png)
- Adición y Prorroga
![adicion prorroga_actual_argo](https://user-images.githubusercontent.com/42418412/103042426-90d7fa00-4547-11eb-95f4-5708f73b016a.png)
así como la información de la póliza para las dos
![poliza_argo](https://user-images.githubusercontent.com/42418412/103042449-a3eaca00-4547-11eb-9203-833274041cb2.png)

Mediante el modulo de novedades se replicaría la siguiente información
- Cesión
![cesion_replica_argo](https://user-images.githubusercontent.com/42418412/103042670-6a668e80-4548-11eb-9be2-1b85fb32863c.png)
- Adición y Prorroga
![adicion prorroga_replica_argo](https://user-images.githubusercontent.com/42418412/103042679-70f50600-4548-11eb-8d9d-c51cc4dfa677.png)

siendo necesario ingresar la información de la póliza y el plazo_ejecución para los dos y modificar los siguientes valores por nulo
- Cesión
       numero_cdp
       vigencia_cdp
       valor_novedad
- Adición y Prorroga 
       contratista
