### ISSUE TITLE
Solución de vulnerabilidades del sistema

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/novedades_cliente#139]
Tomar los resultados de las pruebas de pentesting y evaluacion de vulnerabilidades para hacer las correcciones pertinentes en el sistema

https://drive.google.com/drive/u/0/folders/1slEaNK9_fcZkJ1SLSrvs8Wt6xl6V1P8b

- [x] Absence of Anti-CSRF Tokens
- [x] Cross-Domain JavaScript Source File Inclusion
- [x] Private IP Disclosure 
- [x] npm audit fix

**Comment by JuanCamiloMartinezLopez** [comment]
### Solución Cross-Domain JavaScript Source Inclusion
Este problema ocurre por la peticion de scripts de terceros que pueden traer vulnerabilidades no controladas, para el caso concreto serian dos scripts que son llamados en el **index.html** :
- 64b53ddd5b.js:
![error_seguridad_1](https://user-images.githubusercontent.com/42418412/105879433-2b58ac80-5fd0-11eb-9bd5-449126f19e00.png)
- angular-material.min.js
![error_seguridad_2](https://user-images.githubusercontent.com/42418412/105879455-31e72400-5fd0-11eb-8a3b-66ab8bf8c16b.png)

este se soluciona teniendo estos scripts en archivos propios localizados en **app/core/scripts**, los cuales son llamados en cambio de los anteriores.
![scripts_1](https://user-images.githubusercontent.com/42418412/105879752-8db1ad00-5fd0-11eb-85b7-d73e91a6592e.png)
![solucion_1](https://user-images.githubusercontent.com/42418412/105879923-bfc30f00-5fd0-11eb-8e85-69b449a9f7fd.png)
![solucion_2](https://user-images.githubusercontent.com/42418412/105879929-c0f43c00-5fd0-11eb-9f73-d252d92eaec6.png)

**Comment by JuanCamiloMartinezLopez** [comment]
### Solución Private IP Disclosure
Esta vulnerabilidad se da ya que dentro de **app/scripts/services/config.js**, archivo anteriormente usado para variables de entorno se encuentra algunas que muestran directamente la IP del servicio al que apuntan, aunque no los usan, por lo que se opta por eliminar estas variables.
- ACADEMICA_SERVICE:
![error_seguridad_3](https://user-images.githubusercontent.com/42418412/105880971-f6e5f000-5fd1-11eb-936a-aaa3a94b657b.png)
- SICAPITAL_SERVICE:
![error_seguridad_4](https://user-images.githubusercontent.com/42418412/105880990-fbaaa400-5fd1-11eb-900b-19af0bb43997.png)

**Comment by JuanCamiloMartinezLopez** [comment]
### SOLUCIÓN VULNERABILIDADES PENTESTING
<hr>

- **Exposición de información en sensible en la consola del navegador** 
Se eliminan todos los consol.log() del código.
- **Números Negativos en Formularios**
Se agrega la propiedad min="0" a los inputs  **numero_solicitud** y **numero_oficio** de la vista de **app/views/seguimientoycontrol/legal/acta_terminacion_liquidacion_bilateral.html**, asi como en el input **num_oficio** de la vista de **app/views/seguimientoycontrol/legal/acta_cesion.html**.
Los inputs asociados a valores monetarios no son tocados a falta de claridad sobre la lógica del negocio.
- **No existe restricción de acceso por roles** 
se corrige la petición para obtener el menú según los roles, donde estaba el rol de **ADMINISTRADOR_POLUX** otorgando a todos los usuarios este rol, se ajusta para realizar con los roles otorgados por el token de WSO2.
![roles_peticion](https://user-images.githubusercontent.com/42418412/106079641-9b0b8c00-60e3-11eb-99a5-cf92bf2e4a20.png)

**Comment by diagutierrezro** [comment]
### SOLUCIÓN VULNERABILIDADES DE DEPENDENCIAS
<hr>

- Se ejecuta el comando **npm audit fix** para que se corrijan automaticamente la mayor cantidad de dependencias posibles de manera automatica
- Despues de ejecutar npm audit se realiza la actualización de varias dependencias de manera manual ejecutando los siguientes comandos
![image](https://user-images.githubusercontent.com/38676533/106171186-4574c500-615f-11eb-95ad-49168857454f.png)

- Algunas dependencias no se pueden actualizar ya que genera fallos en el sistema, estas dependencias son **grunt-contrib-connect** la cual genera error al ejecutar el cliente  como se muestra a continuación
![image](https://user-images.githubusercontent.com/38676533/106171427-85d44300-615f-11eb-8d0b-2b04a5127cce.png)

La otra dependencia encontrada que no se puede actualizar es grunt-wiredep ya que si bien ejecuta bien el cliente al momento de abrirlo este se queda cargando:
![image](https://user-images.githubusercontent.com/38676533/106171540-a4d2d500-615f-11eb-817e-fd0a6173ff86.png)

Con el proceso mencionado anteriormente se pasa de mas de 400 vulnerabilidades por dependencias a 116

**Comment by JuanCamiloMartinezLopez** [comment]
### Vulnerabilidad Absence of Anti-CSRF Tokens
<hr>

Este problema resultaba por el uso de etiquetas **form** en las vistas, que eran usadas por las propiedades de verificación de formulario para validar, mas no eran usados para hacer directamente ninguna petición HTTP por lo que era mas complejo usar esta vulnerabilidad para atacar, también las peticiones hacen uso del token de WSO2 por lo que dificulta la falsificación de petición, por lo que falsa vulnerabilidad.

**Comment by ddguerra90** [comment]
Se corrigen las vulnerabilidades presentadas y se mencionan en el siguiente kanban https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=39739

**Comment by ddguerra90** [comment]
Se adjunta nuevo informe en donde no se detectan nuevas vulnerabilidades 
https://docs.google.com/document/d/1VxKi0PSAKiLyLv1tpTeBNHHjXXil8vQGNulyneGninE/edit
