### ISSUE TITLE
Análisis del cliente actual de Argo

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#15]
se requiere analizar el cliente, realizar las instalaciones necesarias para retomar el desarrollo de este cliente.

teniendo en cuenta:

- la bases de datos donde se montara.
- el api NoSql donde se ejecutar.
- El cliente donde se ejecutara o desplegara.

que fallas o mejores son pertinentes para su funcionamiento básico en comparación con otros clientes desarrollados en angular js

**Comment by anlramirezs11** [comment]
La ruta para acceder al modulo de novedades es: /seguimientoycontrol/legal

TODO's: 
* Autenticación.
* Menú en ambiente de desarrollo. (Se sugiere comentariar el menú actual que es el de producción y añadir el menú de desarrollo ).
* Guardar los pdfs en nuxeo.

**Comment by BOTOOM** [comment]
okay, eso va para issue, gracias
