### ISSUE TITLE
Creación de Mock-ups - Novedades

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#156]
Se debe realizar la creación de Mock-ups relacionados con la "optimización del subsistema de gestión contractual y compras (ARGO), en cuanto a: generación de mas de una novedad por contrato".

Se debe tener en cuenta:

- Paleta de colores utilizada en ARGO.
- Simulación del flujo de trabajo.
- Otros escenarios en los que se pueden o deben ajustar parámetros.

**Criterios de aceptación**

- [x]  documento con Mock-ups (acorde a los formatos/lineamientos de la OAS) a ser presentado en Mesas de Trabajo con clientes/usuarios, cuya firma de aprobación dará inicio al desarrollo.

**Comment by a52290451** [comment]
Tomar como guía las historias de usuario registradas en #157 .

**Comment by ricardoavendano** [comment]
Se crea mock up inicial
[mockup1.pdf](https://github.com/udistrital/novedades_cliente/files/6905444/mockup1.pdf)

**Comment by ricardoavendano** [comment]
Mockup 2
[mockup2.pdf](https://github.com/udistrital/novedades_cliente/files/6925592/mockup2.pdf)

**Comment by ricardoavendano** [comment]
Mockup 3
[mockup3.pdf](https://github.com/udistrital/novedades_cliente/files/6925724/mockup3.pdf)

**Comment by a52290451** [comment]
Se validan Mock-Ups propuestos.

**Comment by Astaroth31** [comment]
Se verifican los flujos por roles y se hace adjunta la propuesta
[PROPUESTA DE MOCKUP PARA NOVEDADES.pdf](https://github.com/udistrital/novedades_cliente/files/7950518/PROPUESTA.DE.MOCKUP.PARA.NOVEDADES.pdf)
