### ISSUE TITLE
Propuesta del plan de trabajo (módulo de novedades).

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#158]
Proponer el plan de trabajo para cubrir los requerimientos relacionados con el modulo de novedades.

**Nota**:
Se debe tomar en consideración la validación del estado actual del sistema, el análisis de requerimientos realizado en [Introducción al sistema ARGO](https://github.com/udistrital/cumplidos_mid/issues/30) y las [Historias de Usuario](https://github.com/udistrital/novedades_cliente/issues/157) proporcionadas para el modulo.

De igual forma, se debe asignar prioridad y un estimado de tiempo a cada item.

**Criterios de aceptación**

- [ ] Documento con la propuesta de trabajo realizada (Formato del documento libre).

**Comment by ricardoavendano** [comment]
[Plan de trabajo modulo novedades.docx](https://github.com/udistrital/novedades_cliente/files/6880750/Plan.de.trabajo.modulo.novedades.docx)

**Comment by a52290451** [comment]
Se valida propuesta presentada para el módulo de novedades.
