### ISSUE TITLE
Desarrollo de la interfaz en el cliente.

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#159]
Desarrollar la interfaz grafica necesaria para la interacción del usuario, conforme a lo acordado en reuniones con el cliente (Crear novedad, listar novedades, descargar Acta).

**Criterio de aceptación**

- [x] Creación de rama Feature de desarrollo en novedades_cliente.

Nota: tomar como referencia los [Mock-Ups](https://github.com/udistrital/novedades_cliente/issues/156) diseñados posterior a su aprobación.

**Comment by ricardoavendano** [comment]
Se realiza ajuste para listar las novedades por contrato y vigencia, así mismo se permite visualizar el documento de la novedad para que pueda ser descargado, se actualiza la información de la pantalla inicial con la ultima novedad registrada
https://github.com/udistrital/novedades_cliente/pull/169
