### ISSUE TITLE
Almacenamiento y consulta de documentos mediante gestor_documental_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#166]
Realizar la conexión con el API gestor_documental_mid para almacenar y consultar documentos.

**Criterio de aceptación**

- [x] Commit en rama Feature con implementación.

**Nota**: tomar en consideración el desarrollo realizado en:

1. [ISSUE #79.](https://github.com/udistrital/evaluacion_cliente/issues/79)
2. [ISSUE #75.](https://github.com/udistrital/evaluacion_cliente/issues/75)
3. [ISSUE #96.](https://github.com/udistrital/evaluacion_cliente/issues/96)
4. [Tablero con issues en git.](https://github.com/orgs/udistrital/projects/19?card_filter_query=label%3Acertificacion)
5. [ISSUE #121.](https://github.com/udistrital/evaluacion_cliente/issues/121)

**Comment by ricardoavendano** [comment]
Se realiza PR para ajustar documentación de swagger y routers
https://github.com/udistrital/novedades_crud/pull/24

**Comment by ricardoavendano** [comment]
Mid: Se crea función para guardar documentos en nuxeo con la implementación del gestor_documental_mid
https://github.com/udistrital/novedades_mid/pull/38
