### ISSUE TITLE
Pruebas unitarias y refactor

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#168]
Implementar pruebas unitarias y refactor si es necesario, relacionadas con el módulo de novedades.

**Criterios de aceptación**

- [x] Registro de pruebas unitarias desarrolladas, junto con los resultados obtenidos.

**Material de apoyo:**

Utilizar esta [plantilla](https://docs.google.com/document/d/1Uuk4IQHjhwm-3rQWwsmZQ5uts6X3SCEJ8OpJEsvUHXU/edit?usp=sharing) como guía para el desarrollo de pruebas unitarias.

**Comment by ricardoavendano** [comment]
Se realiza refactor en el cliente y en el mid de novedades, en el cliente se implementa el gestor_documental_mid
commit: https://github.com/udistrital/novedades_cliente/pull/169
https://github.com/udistrital/novedades_mid/pull/37
