### ISSUE TITLE
Propuesta de plan de trabajo - Segundo alcance

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#198]
Presentar la propuesta del plan de trabajo asociada al segundo alcance del modulo de novedades:

- Optimización del subsistema de gestión contractual y compras (ARGO), en cuanto a Flujo de creación, validación y aprobación de novedades contractuales incluyendo los roles de supervisor, OAJ Y ordenador del gasto.

**Criterio de aceptación**

- [x] Documento con propuesta de plan de trabajo en donde se evidencien tareas a realizar y tiempos estimados.

**Comment by ricardoavendano** [comment]
Se crea documento con las actividades a realizar y estimaciones para el segundo requerimiento
[Plan de trabajo modulo novedades 2.docx](https://github.com/udistrital/novedades_cliente/files/7388580/Plan.de.trabajo.modulo.novedades.2.docx)

**Comment by a52290451** [comment]
Se define nuevo plan de trabajo para el segundo alcance de novedades con una duración de 3 semanas:
[Sprint Planning - 14-02-2022.docx](https://github.com/udistrital/novedades_cliente/files/8073980/Sprint.Planning.-.14-02-2022.docx)
