### ISSUE TITLE
Ajustar plantillas de novedades

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#202]
Se requiere ajustar las plantillas de novedades utilizadas en el modulo, de acuerdo a las proporcionadas por la Oficina Asesora Jurídica.

**Criterios de aceptación**

- [x] Commit con cambios asociados a la modificación de formatos para novedades.

**Comment by mantnicot** [comment]
Se realiza las plantillas de 
[acta_suspension.txt](https://github.com/udistrital/novedades_cliente/files/8075033/acta_suspension.txt)
[acta_terminacion_liquidacion_bilateral.txt](https://github.com/udistrital/novedades_cliente/files/8075034/acta_terminacion_liquidacion_bilateral.txt)

**Comment by a52290451** [comment]
Faltan pruebas y despliegue en producción

**Comment by Astaroth31** [comment]
Se actualizan plantillas y se corrigen bugs en el sistema para su estabilización, se adjunta checklist para despliegue
[FormatoEstabilizaciónSistemasEntornoPreProducción(tecnico)V.1 (2) (2).docx](https://github.com/udistrital/novedades_cliente/files/8263273/FormatoEstabilizacionSistemasEntornoPreProduccion.tecnico.V.1.2.2.docx)
.
