### ISSUE TITLE
Flujo de acciones para el Rol de Supervisor y Jurídica

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#203]
Se deben especificar los flujos de acciones que estarán disponibles en el modulo para cada rol mencionado, según los tipos de novedades contemplados.

**criterios de aceptación**

- [x] Presentación de diagramas de flujo a ser implementados en el módulo.

**Comment by ricardoavendano** [comment]
Se realiza ajuste en cliente de novedades para estabilizar version en pruebas y prd
https://hubci.portaloas.udistrital.edu.co/udistrital/novedades_cliente/265
https://hubci.portaloas.udistrital.edu.co/udistrital/novedades_cliente/266
https://github.com/udistrital/novedades_cliente/pull/204
https://github.com/udistrital/novedades_cliente/pull/205

**Comment by ricardoavendano** [comment]
Se crea mockup con flujo para supervisor y jurídica
[Flujo para Supervisor y Juridica.pdf](https://github.com/udistrital/novedades_cliente/files/7664711/Flujo.para.Supervisor.y.Juridica.pdf)

**Comment by a52290451** [comment]
Se valida propuesta de flujo de acciones para supervisor y Jurídica con las siguientes observaciones:

1. Se debe contemplar sistema de notificaciones para firma y validación de novedades.
2. La creación de novedades solo debe estar habilitada para el rol de supervisor quien será el que inicie cada flujo.
3. Se requiere definir la forma de validar, firmar y autenticar las novedades por parte de Jurídica.

**Comment by Astaroth31** [comment]
Se crea diagrama de flujo para Supervisor y Jurídica,  cabe anotar que lo que está en azul es el flujo en común de los dos roles, y lo que está en amarillo es lo que está pendiente por hacer según documentación.

[Flujo Roles Novedades OAS.pdf](https://github.com/udistrital/novedades_cliente/files/7822024/Flujo.Roles.Novedades.OAS.pdf)

**Comment by Astaroth31** [comment]
Para el informe de actividades para seguir con el segundo alcance del proyecto, se obtienen las siguientes actividades que se realizaron:
[Informe Enero.odt](https://github.com/udistrital/novedades_cliente/files/7975850/Informe.Enero.odt)
