### ISSUE TITLE
Creación y ejecución de ETL

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#288]
Se requiere realizar la migración de datos de novedad_poscontractual en ARGO al esquema de novedades en Novedades mediante un ETL, de acuerdo a las siguientes actividades:

1. Análisis de esquema novedades y su equivalente en argo.novedad_poscontractual.
    Fecha fin: 08/06/2022
2. Consulta de información en BDs complementarias: 
    Fecha fin: 09/06/2022 
3. Elaboración de ETL en python (implica elaboración de lógica particular por cada tipo de novedad y las propiedades que se requieren):
    Fecha fin: 13/06/2022
4. Ejecución de ETL en pruebas:
    Fecha fin: 14/06/2022
5. Pruebas funcionales en pruebas y corrección de errores:
    Fecha fin: 15/06/2022
6. Puesta en producción (correr ETL en producción):
    Fecha fin: 16/06/2022

**Comment by Yaov05** [comment]
Se realizó el análisis de los esquemas de argo y novedades para realizar el ETL y se llegó a la conclusión de que se haga usando un script usando python que lo realice, para poder usar el id de la novedad registrada para insertar registros en las demás tablas:

![image](https://user-images.githubusercontent.com/42217637/173937583-470337f0-8c7c-4727-a760-5c125ed0a9cb.png)

![image](https://user-images.githubusercontent.com/42217637/173940646-d998171e-7af8-4bec-bcd1-c6953ac13bb2.png)

**Comment by Yaov05** [comment]
El ETL se volvió a ejecutar en pruebas debido a un fallo en el sistema novedades provocado por el mismo, agregando una propiedad faltante en la tabla propiedad del esquema "novedades" correspondiente a la identificación del contratista en las novedades otrosí.

Se adjuntan archivos con script usados para ejecutar el ETL en pruebas:

https://drive.google.com/drive/folders/1RKuUG5lRiZf2Xum6gMk2_U9sygvhadw9?usp=sharing

**Comment by a52290451** [comment]
Se requiere ejecutar ETL nuevamente en producción.

**Comment by Yaov05** [comment]
Instrucciones de ejecución:

Para ejecutar el ETL, basta con que los archivos estén dentro de una misma carpeta. El archivo llamado "env_db.ini" tiene los datos necesarios para la conexión con las bases de datos (Hay que completar los campos correspondientes a usuario y contraseña).

El código principal se encuentra en el archivo "main.py", que es el que hay que ejecutar (Hay que tener Python instalado).

Se puede desde la terminal, entrando en la carpeta en la que están los archivos y escribiendo el siguiente comando:

`py main.py`

Esto durará varios minutos ejecutándose

**Comment by a52290451** [comment]
Se realiza solicitud de ejecución de ETL en ambiente de producción, de acuerdo a las instrucciones señaladas:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=49327

**Comment by a52290451** [comment]
Se realiza sincronización de datos de forma exitosa
