### ISSUE TITLE
Alimentación del modelo de datos con campos paramétricos de RP y Vigencia RP en propiedades, y Elaboración de ETL

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#313]
Se requiere incluir en la tabla "tipo propiedad" la propiedad "numero_rp" y "vigencia_rp" de forma paramétrica.

Elaborar ETL de migración de datos de RPs y vigencia de RPs desde archivo Excel a Esquema de Novedades, tenien presente la concordancia con los registros ya existentes dentro del esquema.

**Criterios de aceptación**

- [x] Alimentación del modelo de datos con campos paramétricos.
- [x] Elaboración de ETL.
- [x] Ejecución de ETL en ambiente de pruebas
- [x] Pruebas del resultado de la ejecución del ETL.
- [x] Ejecución de ETL en ambiente de producción.

**Comment by Yaov05** [comment]
Se adjunta el archivo con el script para ingresar los registros de la tabla tipo_propiedad para su ejecución en producción (En pruebas ya fue ejecutado)

https://drive.google.com/file/d/1ir5UxpN4eflcj5q7D1F4hNNhTJLJ5ZWg/view?usp=sharing

**Comment by a52290451** [comment]
Se realiza solicitud de ejecución de Script en ambiente de producción:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=49264

**Comment by a52290451** [comment]
Se ejecuta de forma satisfactoria la solicitud realizada

**Comment by Yaov05** [comment]
En el siguiente enlace están los archivos necesarios para ejecutar el ETL relacionado con el registro de RP y vigencia RP:
https://drive.google.com/drive/folders/1Xkol4VvA--ROybsWPjzE5OxyK9Y19HPV?usp=sharing
