### ISSUE TITLE
Desarrollo de mockups y lógica para CDP y vigencia CDP

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#315]
Crear campos en el cliente para ingresar información de CDPs y vigencia de CDPs, y desarrollar la lógica para cargar CDPs disponibles en la novedad, registrar información de los CDPs y actualizar a través de los endpoints disponibles de JBPM.

**Nota:** el ingreso de CDPs debe ser de acuerdo a una lista precargada de CDPs disponibles. (Tomar como ejemeplo lo implementado en Resoluciones V2)

**Criterios de aceptación**

- [x] Commit en ambiente de pruebas.
- [x] Pruebas funcionales de lo implementado.
- [x] Commit en ambiente de producción.
- [x] Estabilización del sistema en producción.

**Comment by a52290451** [comment]
Se requiere adjuntar evidencia de las tareas solicitadas

**Comment by Yaov05** [comment]
En este commit se encuentran los cambios relacionados al CDP y vigencia CDP (Novedades_Cliente):
https://github.com/udistrital/novedades_cliente/commit/6f05cf79a6b737da0c1ca9afe059ae5c0d571913

Y en el siguiente Issue muestra commits y resultado de la prueba de estos campos de CDP:
https://github.com/udistrital/novedades_cliente/issues/316

**Comment by Yaov05** [comment]
Se adjuntan checklist para el cliente y mid de Novedades:

[(NOVEDADES)FormatoEstabilizaciónSistemasEntornoProduccion.docx](https://github.com/udistrital/novedades_cliente/files/9688068/NOVEDADES.FormatoEstabilizacionSistemasEntornoProduccion.docx)

[(NOVEDADES_MID_CRUD)FormatoEstabilizaciónSistemasEntornoProduccion.docx](https://github.com/udistrital/novedades_cliente/files/9688069/NOVEDADES_MID_CRUD.FormatoEstabilizacionSistemasEntornoProduccion.docx)
