### ISSUE TITLE
Desarrollo de mockups y lógica para RP y vigencia RP

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#316]
Crear campos en el cliente para ingresar información de RPs y vigencia de RPs, y desarrollar la lógica para cargar RPs disponibles en la novedad, registrar información de los RPs y actualizar a través de los endpoints disponibles de JBPM.

**Nota:** el ingreso de RPs debe ser de acuerdo a una lista precargada de RPs disponibles. (Tomar como ejemeplo lo implementado en Resoluciones V2)

**Criterios de aceptación**

 - [x] Commit en ambiente de pruebas.
 - [x] Pruebas funcionales de lo implementado.
 - [x] Commit en ambiente de producción.
 - [x] Estabilización del sistema en producción.

**Comment by Yaov05** [comment]
Commits con cambios relacionados con la estructura del post de la novedad adición/prórroga (MID):

https://github.com/udistrital/novedades_mid/commit/d913c18a56841e9ab28a395013a5f8a3076ca3aa

https://github.com/udistrital/novedades_mid/commit/0cee1598e8f749070cfa059ccabad38f20c3fa6f

Commits relacionados con la interfaz y la lógica de la novedad adición/prórroga con RP y vigencia RP (Cliente):

https://github.com/udistrital/novedades_cliente/commit/6f05cf79a6b737da0c1ca9afe059ae5c0d571913

**Comment by a52290451** [comment]
Queda pendiente realizar despliegue en ambiente de producción.

**Comment by a52290451** [comment]
Faltan realizar pruebas.

**Comment by Yaov05** [comment]
Actualmente el sistema funciona correctamente en lo relacionado al RP y vigencia RP, el usuario selecciona de una lista de CDPs disponibles y según el seleccionado, llena el campo de RP automáticamente:

![image](https://user-images.githubusercontent.com/42217637/192936422-bdf31c28-d7e8-438f-a806-5305b7fd8942.png)

**Comment by a52290451** [comment]
Se realiza despliegue de API MID en ambiente de producción - https://hubci.portaloas.udistrital.edu.co/udistrital/novedades_mid/92/1/7
