### ISSUE TITLE
Despliegue en producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#318]
Realizar la gestión necesaria para desplegar el sistema de Novedades en ambiente de Producción.

**Criterios de aceptación**

 - [x] CheckList de requerimientos.
 - [x] Despliegue del cliente.
 - [x] Despliegue del API Mid.
 - [x] Despliegue del API Crud.
 - [x] Estabilización del sistema en producción.

**Comment by Yaov05** [comment]
Se adjunta link al checklist de requerimientos que se está siguiendo y se encuentra en proceso
https://docs.google.com/spreadsheets/d/1SYlSpl70mKMVmh_VUnDgi8kKIE6qRu1JeO5FQsLZzaE/edit?usp=sharing

**Comment by Yaov05** [comment]
En este caso en particular no fue necesario el despliegue del crud ya que no se realizaron cambios, el cliente y el mid se encuentran desplegados en pruebas y funcionando, faltando solamente realizar el merge desde la rama de pruebas hacia producción para ambos repositorios (Mid y Cliente)

**Comment by a52290451** [comment]
Se requiere realizar el despliegue en producción, posterior al cumplimiento de todos los puntos señalados en el checklist correspondiente.
