### ISSUE TITLE
Corrección Bug - Novedad de Adición/Prórroga

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#332]
Se requiere corregir el siguiente Bug en novedades de Adición/Prórroga:

- Las novedades de otro sí o Adición/Prórroga no se están registrando correctamente, por lo que el valor o las fechas del contrato no se alteran, algo que no debe ocurrir (Esto ocurre tanto para novedad de adición o prórroga por separado o una adición y prórroga).

**Criterios de aceptación**

- [x] Commit en ambiente de pruebas.
- [x] Pruebas funcionales.
- [x] Checklist de despliegue en producción
- [x] Commit en ambiente de producción.
- [x] Estabilización del sistema en producción.

**Comment by Yaov05** [comment]
Commit con cambios realizados:
https://github.com/udistrital/novedades_mid/commit/04a659e244d8c5d76450c0e2551866b7e185ad53
