### ISSUE TITLE
Ajustes Visuales, de restricciones y de codigo quemado

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#333]
Se requieren realizar los siguientes ajustes visuales y de restricciones:

- Ajustar el campo "Número Solicitud" en  Novedades de Reinicio - Información de la novedad para no permitir mas de 7 digitos.
- Ajustar letrero del formulario "información" en "Novedades de Terminación anticipada" por "INFORMACIÓN DE LA NOVEDAD".
- Eliminar código quemado "Console.log" que muestra información por consola en diferentes solicitudes.

**Criterios de aceptación**

- [x] Commit en ambiente de pruebas.
- [x] Pruebas funcionales.
- [x] Checklist de despliegue en producción
- [x] Commit en ambiente de producción.
- [x] Estabilización del sistema en producción.

**Comment by Yaov05** [comment]
Commit con los ajustes requeridos realizados
https://github.com/udistrital/novedades_cliente/commit/ff9b4a4d947f5b37d9d6ffb35acdd1f691f9bac7

**Comment by Yaov05** [comment]
Checklist del cliente:
[(NOVEDADES)FormatoEstabilizaciónSistemasEntornoProduccion.docx](https://github.com/udistrital/novedades_cliente/files/9735388/NOVEDADES.FormatoEstabilizacionSistemasEntornoProduccion.docx)
