### ISSUE TITLE
Complemento de registros de novedades antiguas (RP y Vigencias RP) mediante ETL - en Producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#336]
Se requiere completar registros antiguos de novedades de adición/prorroga que no cuentan con información asociada a RP y Vigencia RP, en ambiente de producción.

Se debe solicitar a DBAs la ejecución del ETL registrado en comentarios en ambiente de producción. 

**Criterios de aceptación**

- [x] Solicitud de ejecución de ETL en producción.
- [ ] Validación de cambias realizados.

**Comment by a52290451** [comment]
En el siguiente link se encuentra la información asociada al ETL
https://github.com/udistrital/novedades_cliente/issues/313#issuecomment-1264011505

**Comment by a52290451** [comment]
Se realiza solicitud de ejecución de Script en ambiente de producción
https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=49388

**Comment by Yaov05** [comment]
https://drive.google.com/drive/folders/1Xkol4VvA--ROybsWPjzE5OxyK9Y19HPV?usp=sharing

**Comment by a52290451** [comment]
Se valida carga de datos en producción
