### ISSUE TITLE
Control de Fallos en Novedades de Otro Si y Cesión

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#347]
Se requiere reaizar el control de fallos en funcionalidades no soportadas por el sistema:

- Cuando se realiza doble cesión en un contrato.
- Cuando se realiza doble Novedad de tipo Otro si.

Se requiere mostrar un mensaje que indique que este tipo de casos no se encuentran soportados en el sistema.

**Criterios de aceptación**

- [x] Commit en pruebas con correcciones realizadas.
- [x] Pruebas funcionales.
- [x] Checklist de despliegue en producción.
- [x] Commit en ambiente de producción.
- [x] Estabilización del sistema en producción.

**Comment by Yaov05** [comment]
Luego de realizar pruebas en el sistema, se tiene que se muestra la siguiente alerta cuando se intenta crear una novedad de cesión dos veces para el mismo contrato:

![image](https://user-images.githubusercontent.com/42217637/195903441-b8649266-927d-429a-acc1-e2dc07b6d10f.png)

Por otro lado, se muestra lo siguiente cuando se quiere crear dos veces el mismo tipo de novedad otro sí (Adición y/o Prórroga) para el mismo contrato:

![image](https://user-images.githubusercontent.com/42217637/195906251-2de4b9f0-0592-4c8b-8cfa-e776d886855b.png)

**Comment by Yaov05** [comment]
Checklist para el despliegue:
[(NOVEDADES)FormatoEstabilizaciónSistemasEntornoProduccion.docx](https://github.com/udistrital/novedades_cliente/files/9788864/NOVEDADES.FormatoEstabilizacionSistemasEntornoProduccion.docx)

**Comment by a52290451** [comment]
Se validan pruebas funcionales realizadas.

De acuerdo con el checklist de despliegue a producción. Se solicita realizar PR de la rama Release a Master.

**Comment by a52290451** [comment]
Se realiza despliegue exitoso a producción.

https://hubci.portaloas.udistrital.edu.co/udistrital/novedades_cliente/446
