### ISSUE TITLE
HU1 - 1 - Elaboración de Mockups para lista de novedades

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#348]
Se requiere eleborar mockups para mostrar la lista de novedades del contrato seleccionado en una sección en la parte inferior de la página, con las acciones "Ver" y "Editar" por novedad.

La lista debe contener los siguiente campos:
- Nombre
- Enlace
- Fecha de creación
- Acciones

**Criterios de aceptación**

- [x] Mockups para el desarrollo.

Sugerencias: 
1. Las acciones "Ver" y "Editar" por novedad deben estar señaladas con ICONOS.
2. Se debe mantener la paleta de colores del subsistema.

**Comment by Yaov05** [comment]
Se adjunta imagen del mockup de la lista de novedades:

![image](https://user-images.githubusercontent.com/42217637/196579548-8bcd1304-3aa2-4793-b568-ee56333bd3ab.png)

Los mock-ups se pueden encontrar en el siguiente link:
https://drive.google.com/file/d/1_KDQcUE0Dy60kZc3Bx6mxigYoEWsdOBZ/view?usp=sharing

**Comment by a52290451** [comment]
Correcciones sugeridas:

1. Utilizar paleta de colores en iconos de acciones, por ejemplo:
![image](https://user-images.githubusercontent.com/36229498/196715995-d83c14a1-5023-4ca6-bf3e-b0abf5906333.png)

2. Unificar titulo de sección y titulo de tabla. (dejar uno solo).

3. Utilizar separador de sección como bordes para la tabla y no bordes negros directamente.
4. Añadir separación entre filas con linea tenue. Por ejemplo.
![image](https://user-images.githubusercontent.com/36229498/196717205-feb156af-358a-424a-8592-abeaaebe1ddc.png)

5. Centrar titulos de la tabla.

**Comment by Yaov05** [comment]
Se propone tener la tabla con un título con los colores del sistema o con un texto sencillo

![image](https://user-images.githubusercontent.com/42217637/196824241-72568abb-0920-45f6-b698-f124fd4b13ce.png)

![image](https://user-images.githubusercontent.com/42217637/196824418-e371bcc7-e1a5-4489-934a-185f90505946.png)

**Comment by a52290451** [comment]
Se opta por la segunda opción: "título con los colores del sistema".

**Correciones:**
1. Centrar los titulos de las columnas de la tabla.
2. Eliminar boton de "Ver Novedades". Estas deben cargarse por defecto cuando se cargue el contrato.

Con estos cambios, los mockups quedan aprobados y se da paso al inicio del desarrollo.

**Comment by Yaov05** [comment]
Los mock-ups quedan finalmente de la siguiente manera:
![image](https://user-images.githubusercontent.com/42217637/196833281-97ec5064-a2dd-4063-966e-4f0b3acf3b5f.png)
