### ISSUE TITLE
HU1 - 1 - Desarrollo de Tabla para lista de novedades

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#349]
Se requiere cambiar el modo en que se muestran las novedades asociadas a un contrato de forma tal que se muestre la lista de las novedades del contrato seleccionado en una sección en la parte inferior de la página, con las acciones "Ver" y "Editar" por novedad, y no mediante un cuadro emergente.

**Criterios de aceptación**
 
- [x] Creación de rama Feature
- [x] Commit en pruebas con implementación realizada.
- [x] Pruebas funcionales (Desarrollador).
- [x] Checklist de despliegue en producción.
- [x] Commit en ambiente de producción.
- [x] Estabilización del sistema en producción.

**Comment by Yaov05** [comment]
Commit con cambios realizados:
https://github.com/udistrital/novedades_cliente/pull/366/commits/23c873e26531f24254f126eea0e502eb4b9f2447

**Comment by Yaov05** [comment]
Checklist para despliegue en producción:
[(NOVEDADES)FormatoEstabilizaciónSistemasEntornoProduccion.docx](https://github.com/udistrital/novedades_cliente/files/9861438/NOVEDADES.FormatoEstabilizacionSistemasEntornoProduccion.docx)

**Comment by Yaov05** [comment]
Tras las pruebas funcionales se nota que los colores que en local se ven como en el resto del sistema, no se aplica, este problema es solamente con el sistema desplegado
![image](https://user-images.githubusercontent.com/42217637/197810123-cb24bb93-7a84-4c5f-908a-4d3800aade83.png)

**Comment by a52290451** [comment]
Para despliegue a producción, se requiere adjuntar evidencia de pruebas funcionales realizadas y corrección del bug visual.

**Comment by a52290451** [comment]
Se despliega en producción
