### ISSUE TITLE
HU1 - 3 - Mockups para vista de edición de novedades de adición.

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#351]
Se requiere crear mockups para vista de edición de novedades de "Adición". Estos muckups deben estar basados en la vista de creación de esta novedad y en el análisis previamente realizado.

**Criterios de aceptación**

- [x] Mockups para el desarrollo.

**Consideraciones**
1. Se debe bloquear o no mostrar el campo de selección para Adición y Prorroga.
2. El boton de "Actualizar" debe estar bloqueado.
3. Se debe mantener la paleta de colores del subsistema.

**Nota:** Tomar en consideración el análisis de campos realizado en [HU1 - 3](https://docs.google.com/spreadsheets/d/15zNd-P6Ozmq4lrvKeMzE8o5sAvRm7Blp/edit?usp=sharing&ouid=104124925692794756698&rtpof=true&sd=true)

**Comment by Yaov05** [comment]
Para la interfaz de edición, se usarán los mismos componentes de la de creación de novedades, con la diferencia de que los checkbox que indican el tipo de novedad estarán deshabilitados, ya que no se podrá convertir una novedad de adición, en una de prórroga, por ejemplo.

![image](https://user-images.githubusercontent.com/42217637/197678646-06534a80-9494-4110-bc54-2d726128e039.png)

**Comment by Yaov05** [comment]
Se contempla la posibilidad de que no se pueda modificar los valores de número de solicitud y número de oficio, según comentario hecho en la [HU1 - 3](https://docs.google.com/spreadsheets/d/15zNd-P6Ozmq4lrvKeMzE8o5sAvRm7Blp/edit?usp=sharing&ouid=104124925692794756698&rtpof=true&sd=true)

![image](https://user-images.githubusercontent.com/42217637/197679659-277096bc-845c-46fc-8e62-37bd5937782c.png)

**Comment by Yaov05** [comment]
El botón de actualizar actualmente estará deshabilitado

![image](https://user-images.githubusercontent.com/42217637/197679729-afb1d741-f2e4-41bd-8967-08cd8a4f1512.png)

**Comment by Yaov05** [comment]
Los mockup se podrán encontrar en el siguiente link, en la pestaña llamada "Edición de novedades":
https://drive.google.com/file/d/1_KDQcUE0Dy60kZc3Bx6mxigYoEWsdOBZ/view?usp=sharing

**Comment by a52290451** [comment]
Aclaraciones: 
1. los campos "Número de solicitud" y  "Número de oficio" si podrán ser editados. Esta duda se aclaró tambien con el gerente de proyectos.
2. El formulario de "INFORMACIÓN DE PRÓRROGA" deberá estar oculto. Solo debe mostrarse la información general de la novedad y la "INFORMACIÓN DE ADICIÓN".

Con estos cambios, se aprueban mockups realizados
