### ISSUE TITLE
HU1 - 3 - Análisis para vista de edición de novedades de adición

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#352]
Es necesario analizar de que forma se creara la vista de edición de novedades de acuerdo a implementaciones en otros sistemas. Esto con el objetivo de identificar de que forma puede ser aprovecha la vista de "creación" de novedades para ahorrar tiempos en desarrollo.

**Criterios de aceptación**

- [x] Mejor alternativa de implementación encontrada.

**Nota**: tomar como ejemplo el subsistema de Evaluaciones y de Resoluciones.

**Comment by Yaov05** [comment]
Luego de analizar las herramientas que ofrece Angular JS, y revisando otros sistemas que cuentan con funcionalidades similares a la que se requiere implementar. Se concluye que se puede tener un mismo componente o archivo para crear y editar novedades, validando la información registrada de cada contrato al momento de desplegar el formulario y llenando los campos en caso de ser necesario
