### ISSUE TITLE
modelo de datos novedades pos-contractuales

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#41]
Actualmente se usa una base de datos no relacional en MongoDB, la cual tiene colecciones que pretenden realizar un modelo relacional allí, se había encontrado inconvenientes para pasar este modelo de Mongo a uno relacional .

La colección que mandaba inconvenientes no se usa, así que se procedió a realizar un modelo de datos con el fin de reemplazar mongo.

Por ende se debe de platear un modelo de datos relacional que contemple los distintos tipos de resoluciones

***calidad*** 

- [x] el modelo se ha dado a conocer a los arquitectos, equipo de soporte y DBA.

- [x] el modelo cumple con los lineamientos de la oficina. 

- [x] se realizan cambio y solicitudes dadas después de dar a conocer el modelo. 

- [ ] el modelo pasa a revisión. 

- [ ] modelo aprobado

**Comment by BOTOOM** [comment]
![novedades](https://user-images.githubusercontent.com/28914781/64623767-2aa98100-d3af-11e9-93c8-52b66642d50d.png)

**Comment by jairolh** [comment]
Se realiza la revisión y se tienen las siguientes observaciones:

De acuerdo a los lineamientos de modelos de datos en https://github.com/udistrital/introduccion_oas:

- Adicionar a las tablas los campos de fecha_creacion, fecha_modificacion y activo 
- Adicionar el sufijo "_id", para los campos que se relacionan con tablas de otros esquemas
- Adicionar en un mensaje a que tabla y a que campo del otro esquema hace referencia.

- Se recomienda incluir el campo de vigencia del CDP.
- Se recomienda incluir a la tabla "tipo_propiedad", campo que indique a que tipo de novedad se relaciona.
- Se recomienda actualizar el nombre "novedades" a "novedades postcontractuales"

**Comment by BOTOOM** [comment]
esquema con correcciones

![novedades](https://user-images.githubusercontent.com/28914781/65535750-9f101400-dec7-11e9-8684-c3dad9264f3e.png)

**Comment by BOTOOM** [comment]
@jairolh @corio27 @blacburn @fnrojash 

Ingenieros en la imagen arriba de este comentario esta el modelo de novedades con las respectivas correcciones solicitadas.

los etiqueto por si tienen algún otro aporte sobre el modelo.

se aclara que esto es un modelo para un nuevo esquema

gracias.

**Comment by nodier25** [comment]
Buen día

Se verifican las sugerencia del arquitecto y se revisa el modelo se encuentra ok

Muchas gracias

**Comment by corio27** [comment]
Se válida modelo

**Comment by BOTOOM** [comment]
gracias por sus revisiones, se procede a cerrar el issue

**Comment by jairolh** [comment]
Se verifican ajustes.

Sin embargo, re recomienda en el mensaje donde se indica el campo que se relaciona con otra tablas. indicar el nombre del esquema, con el fin de poder identificar facilmente la relación.
