### ISSUE TITLE
Creación de contratos para pruebas con vigencia 2023

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#424]
Se requiere crear contratos para pruebas con vigencia 2023, que esten registrados en ARGO y liquidados en TITAN, de acuerdo al siguiente documento:

https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EZ5xs4x1bItEiIYfsjLPYY0Bzmx5_OdeTLXxzsCRf2cbnw?e=ZMWhsO

**Criterios de aceptación**

- [x] Evidencia de creación y funcionamiento de contratos de prueba.

**Comment by Yaov05** [comment]
![image](https://user-images.githubusercontent.com/42217637/212344494-70dcbc43-c798-4844-811d-227536d57d3e.png)

![image](https://user-images.githubusercontent.com/42217637/212344789-526fed6e-2d0e-4e5e-8a52-c361079b55fc.png)

![image](https://user-images.githubusercontent.com/42217637/212344947-de52f76a-d119-4154-91fb-210fb6b0f32d.png)

![image](https://user-images.githubusercontent.com/42217637/212345108-22907ef5-b09f-495b-b3bb-4eb8d963f241.png)

![image](https://user-images.githubusercontent.com/42217637/212345313-76dbaa45-e1da-422b-b93b-565ecac5f315.png)
