### ISSUE TITLE
HU2 - 1 - 1&2 - MockUps para vista de "Seguimiento legal" asociada a Contratistas

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#430]
Se requiere realizar los mockups necesarios para vista de seguimiento legal asociada a contratistas, manteniendo la paleta de colores del sistema base.

Lista de mockups:
1. Mensaje de alerta que indica que el contratista no tiene un contrato activo.
2. Vista limitada de "Seguimiento legal" asociada al contratista, en el cual aparezca el información asociada al contrato vigente.

**Criterios de aceptación**

- [x] Creación de mockups.
- [ ] Revisión  y aceptación de mockups.

Nota: tomar como referencia las indicaciones señaladas en las [historias de usuario](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BF7AE9E4A-FDD7-5215-71CF-93EC3253ECB7%7D&file=HU%202%20-%20Novedades%20-%20Segundo%20Alcance%202022.xlsx&action=default&mobileredirect=true).

**Comment by Yaov05** [comment]
Para el desarrollo se proponen los siguientes mock-ups, dejando abierta la posibilidad de que sea mostrado como un mensaje de alerta, de error o de información:

![image](https://user-images.githubusercontent.com/42217637/213205091-470bffb9-29d4-470b-8d6c-77ec63cfbf9a.png)

![image](https://user-images.githubusercontent.com/42217637/213205257-070683c7-e06a-4b37-9363-fc60b281bc50.png)

![image](https://user-images.githubusercontent.com/42217637/213205553-7a8ac332-6623-43a3-9653-ca3aaca3bb41.png)

**Comment by Yaov05** [comment]
Para la vista de seguimiento legal se propone que se muestre unicamente la información del contrato y las novedades, eliminando la posibilidad de crear novedades para el rol de contratista:

![image](https://user-images.githubusercontent.com/42217637/213207097-c6827822-af45-4f47-a5d7-b612bf9a6ce1.png)

**Comment by a52290451** [comment]
Se requiere incluir segmento asociado a la creación de novedades

**Comment by Yaov05** [comment]
Para el desarrollo, dependiendo de la facilidad para que quede bien visualmente se optará por dejar bloqueados los campos de numero de contrato y vigencia o impedir que se muestren, dejando únicamente visible la opción para crear novedades:


![image](https://user-images.githubusercontent.com/42217637/213216375-8bdce4b6-99f2-4db6-9ee7-564604eb6eb3.png)

![image](https://user-images.githubusercontent.com/42217637/213217626-53c48cd6-4e99-40fc-9863-22ec51bba8df.png)

**Comment by a52290451** [comment]
Se elige la opción de dejar los campos bloqueados pero visibles y ocultar el boton de buscar numero contrato
