### ISSUE TITLE
HU2 - 2 - 1 - Mockups para tabla de novedades con columna de "Estado"

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#433]
Se requiere realizar la creación de un mockup que permita visualizar la tabla de "Novedades" de la vista "Seguimiento legal", en la cual se incluya el estado de la novedad.

**Criterios de aceptación**

- [x] Creación de mockups.
- [x] Revisión  y aceptación de mockups.

Nota: tomar como referencia las indicaciones señaladas en las [historias de usuario](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BF7AE9E4A-FDD7-5215-71CF-93EC3253ECB7%7D&file=HU%202%20-%20Novedades%20-%20Segundo%20Alcance%202022.xlsx&action=default&mobileredirect=true).

**Comment by Yaov05** [comment]
Mock-ups para la tabla de novedades con la nueva columna relacionada al estado de la novedad:

![image](https://user-images.githubusercontent.com/42217637/213221751-93a25392-d84a-4377-bac8-d2b6c17e56fa.png)
