### ISSUE TITLE
HU 1 - 7 - 1 - Mockups para vista de edición de novedades de Adición y Prórroga.

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#449]
Se requiere crear mockups para vista de edición de novedades de "Adición y Prórroga". Estos muckups deben estar basados en la vista de creación de esta novedad y en el análisis previamente realizado.

**Criterios de aceptación**

- [x] Mockups para el desarrollo.

**Consideraciones**
1. Se debe bloquear o no mostrar el campo de selección para Adición y Prorroga.
2. El boton de "Actualizar" debe estar bloqueado.
3. Se debe mantener la paleta de colores del subsistema.

**Nota:** Tomar en consideración el análisis de campos realizado en [HU1 - 7](https://docs.google.com/spreadsheets/d/15zNd-P6Ozmq4lrvKeMzE8o5sAvRm7Blp/edit#gid=1751145773)

**Comment by Yaov05** [comment]
![image](https://user-images.githubusercontent.com/42217637/216069600-c539d56b-7118-41d8-9624-b592e85a2e30.png)
![image](https://user-images.githubusercontent.com/42217637/216069688-f40c480c-0f5b-4e59-8e5f-3c9bc5e134ad.png)
