### ISSUE TITLE
HU 1 - 9 - 1 - Mockups para vista de edición de novedades de Cesión

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#453]
Se requiere crear mockups para vista de edición de novedades de "Cesión". Estos muckups deben estar basados en la vista de creación de esta novedad y en el análisis previamente realizado.

**Criterios de aceptación**

- [x] Mockups para el desarrollo.

**Consideraciones**
2. El boton de "Actualizar" debe estar bloqueado.
3. Se debe mantener la paleta de colores del subsistema.

**Nota:** Tomar en consideración el análisis de campos realizado en [HU1 - 9](https://docs.google.com/spreadsheets/d/15zNd-P6Ozmq4lrvKeMzE8o5sAvRm7Blp/edit#gid=1104868650)

**Comment by Yaov05** [comment]
![image](https://user-images.githubusercontent.com/42217637/216086322-45a09336-89cc-43e6-ae7a-777f36f4d1a4.png)
