### ISSUE TITLE
HU1 - 11 - 1 - Mockups para vista de edición de novedades de Suspensión

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#458]
Se requiere crear mockups para vista de edición de novedades de "Suspensión". Estos muckups deben estar basados en la vista de creación de esta novedad y en el análisis previamente realizado.

**Criterios de aceptación**

- [x] Mockups para el desarrollo.

**Consideraciones**
2. El boton de "Actualizar" debe estar bloqueado.
3. Se debe mantener la paleta de colores del subsistema.

**Nota:** Tomar en consideración el análisis de campos realizado en [HU1 - 11](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EXw7J518jXFQZlktmLgEEMkBylehZcRb1RdCLDQOP_RkMg?e=NbVrjJ)

**Comment by Yaov05** [comment]
El sistema debe mostrar los datos de la última novedad de suspensión y permitir hacer cambios:

![image](https://user-images.githubusercontent.com/42217637/219062554-a115d24b-5aa1-4dd0-ac85-300e7cc5eb63.png)
