### ISSUE TITLE
Informe final de cierre 2023 -1

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#461]
Se requiere completar el informe final de cierre asociado a NOVEDADES, en el cual se indique:

1. El estado en el cual se entrega el sistema.
2. Las mejoras realizadas.
3. La deuda tecnica del sistema.
4. Los errores conocidos.
5. Limitaciones del sistema
6. Las tareas faltantes por realizar para salir a producción.
7. Los usuarios de prueba activos en el sistema con sus respectivos roles.
8. Videotutoriales y manual de usuario.

Tomar como referencia el [informe de cierre final del periodo anterio](https://github.com/udistrital/novedades_cliente/files/10724321/Diagnostico.Final.Novedades.1.docx), y el formato de informe de cierre del periodo actual.

**Comment by Yaov05** [comment]
[Diagnostico.Final.Novedades.docx](https://github.com/udistrital/novedades_cliente/files/10768007/Diagnostico.Final.Novedades.docx)

**Comment by a52290451** [comment]
Se adjunta informe de diagnostico final actualizado e informe de cierre del proyecto 2022 - 2023.

1. [Informe de diagnostico final de NOVEDADES](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EcIVH9_AgR5GnJW4PPOgaDYBPtfeoj1ZBP6crhTZ2QjDFw?e=7oKC5p)
2. [Informe de cierre de NOVEDADES 2022 - 2023](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EQg1h2X3wb5GrDvL-_TdygkBsrXUxX8lvZeOPpEbmEsi5A?e=DPea8v)
