### ISSUE TITLE
Estructura para crear tablas de unión de datos de argo (sara) y Novedades (mongo)

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#47]
en caso de no aprobarse el modelo de datos relacional se requiere crear una estructura de datos en el almacen de datos en el cual se unifiquen los ID's de novedadpos-contractual (sql) y el id de novedad de mongo

**Comment by BrayanB24** [comment]
Se comienza con el desarrollo.

**Comment by BrayanB24** [comment]
Definido el flujo de como se realizarán las consultas desde Argo novedades hacia el módulo de novedades postcontractuales, debe crearse una tabla que relacionará los ID devueltos de ambos registros en los CRUD de las tablas de Novedades_CRUD y Administrativa_Amazon, para esto, debe crearse un modelo de datos para la tabla que llevará esta relación de ID. Dicha tabla será revisada y luego implementada por el arquitecto en el Almacen de datos y luego consumida desde un servicio de JBPM. El modelo sugerido para la tabla es el siguiente : 

![image](https://user-images.githubusercontent.com/45292226/65256357-05aac180-dac5-11e9-98b7-2242703515f2.png)

**Comment by BrayanB24** [comment]
Se modifica la tabla para cumplir lineamientos de la oficina. 

![image](https://user-images.githubusercontent.com/45292226/65259500-5f61ba80-daca-11e9-853b-eae66f7518ae.png)

**Comment by BOTOOM** [comment]
segun consejos ya dados a otros miembros del equipo se recomienda hacer el siguiente ajuste al modelo:

- ya que hay 2 atributos de la tabla que son referencia a algo externo estas deben de finalizar con `_id` , esto para que al ver el esquema se pueda evidencia que es una referencia a un valor externo, ejemplo: `novedad_id`.
- la fecha de creación no puede llegar a ser nulo ya que se debe de tener registro obligatorio de esta fecha.
- la fecha de modificación también debe ser un `not null` según los lineamientos.

**Comment by BrayanB24** [comment]
Se modifica la tabla siguiendo las recomendaciones hechas por @BOTOOM corrigiendo los _id de los campos que se relacionarán y colocando los campos como not null. 

![image](https://user-images.githubusercontent.com/45292226/65276871-52ef5900-daee-11e9-96a2-2037602179be.png)

**Comment by BrayanB24** [comment]
Por último, revisando con el arquitecto se corrige el esquema a "temporal" que es donde será almacenada la tabla, quedando el modelo de la siguiente manera: 

![image](https://user-images.githubusercontent.com/45292226/65279499-f98a2880-daf3-11e9-8adc-3f8dc5e7c2cd.png)

**Comment by BrayanB24** [comment]
El modelo de la tabla ha sido enviado al arquitecto y se espera que este sea implementado, mientras se aprueba el modelo general de novedades contractuales para poder continuar con el desarrollo del API MID de novedades.

**Comment by BOTOOM** [comment]
la tarea se da por cumplida y se procede a cerrar el issue
