### ISSUE TITLE
crear registro de tipo novedad en parametros_gobierno

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#48]
con el fin de centralizar los datos de tipos de novedades

es necesario crear los registro de los datos de los diferentes tipos de novedades en `parametros_gobierno` , esto permitiendo su uso para Argo y su uso en Novedades (al momento de quitar la base de datos de mongo)

para completar dicha tarea se recomienda: 

- [x] revisar el api de parámetros gobierno y a donde se apunta. 

- [ ] si la estructura de dicha api es genérica : 
    - [ ] abstraer el modelo para poder ingresar tipos de novedades de manera adecuada.
    - [ ] proponer estructura de datos a enviar al api (json)

- [x] si no esta generica la estructura del api, proponer alternativas, ya sea en el esquema del crud de novedades o tablas adicionales para el modelo de `parametros_gobierno`

----

Cualquier novedad comentarla en el presente issue

**Comment by BrayanB24** [comment]
Se comienza con la ejecución de la tarea.

**Comment by BrayanB24** [comment]
Haciendo un análisis previo el API de parámetros gobierno todavía está en fase de desarrollo por lo que no se ha contemplado todavía una tabla en donde se especifiquen parámetros. Debe consultarse con el equipo correspondiente (core) como debe empezar el proceso, si crear una tabla nueva o esperar al desarrollo.

**Comment by BrayanB24** [comment]
Realizando la consulta con el equipo encargado de parametros_gobierno (core) indican que el procedimiento debería ser el siguiente:

- Dicha API no tiene una estructura general para los parámetros por lo que se debe crear una nueva tabla en donde estarán soportados los tipos de novedades en tablas paramétricas.

- Diseñar la estructura de la tabla que será almacenada en el esquema de la API parametros_gobierno.

- Obtener aprobación por parte de los DBA para el script que genera la tabla del esquema de parámetros gobierno.

- Proporcionar al equipo core el script sql para que ellos lo ejecuten y creen las rutas correspondientes del API.

Por lo tanto se queda a la espera de la construcción del script de la tabla. @BOTOOM

**Comment by BOTOOM** [comment]
ese proceso a mi parecer no es correcto para lo que necesitamos, este proceso es innecesario para el negocio. se tenia pesado que la estructura de `parametros_gobierno`, era una estructura general donde se tenia la posibilidad de almacenar los datos de varios negocios.

por ende se ha procedido a hablar con el equipo de soporte y con arquitectos, para confirmar el uso de la siguiente propuesta:

-  ya que no tiene sentido el sacar tablas a otro esquema fuera del negocio, la tabla de tipo_novedad con sus respectivos datos ha de pasar a implementarse en el esquema de base de datos sql para novedades #41

**Comment by BOTOOM** [comment]
por ende esta tarea, descrita en el presente issue ya no se realizara
