### ISSUE TITLE
Entrega primer alcance - Novedades

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#484]
Se requiere realizar las tareas necesarias para terminar el desarrollo de novedades en su primer alcance y preparar el ambiente de pruebas para realizar pruebas con soporte de primer y segundo nivel, y pruebas de usuario.

**Especificaciones técnicas**

- Actualmente queda pendiente terminar pruebas funcionales y cargar parte del desarrollo del primer alcance en ambiente de pruebas.

**Sub Tareas**

- [x] Conexión con parametros para obtener el estado de las novedades (el estado se consulta mediante el código de referencia)
- [x] Presentar sistema a gerente general y soporte de primer y segundo nivel.

**Criterios de aceptación**

- [x] El sistema debe estar completamente funcional en ambiente de pruebas con los requerimientos señalados anteriormente.
- [x] El sistema debe estar abalado por el gerente general y soporte de primer y segundo nivel.

**Requerimientos**

- No aplica

**Dependencias**

- titan_mid
- administrativa_amazon_api
- gestor_documental_mid

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Yaov05** [comment]
Commit con la conexión con parámetros desde el mid:
https://github.com/udistrital/novedades_mid/commit/5e8bb4f72f9f876fc2d9467de47d30af472d38b1
