### ISSUE TITLE
Cambio de lógica para consultar novedades

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#486]
Se requiere realizar un cambio de lógica en cuanto a la consulta de novedades postcontractuales para que estas se consulten directamente de la base de datos de novedades y no de documentos_crud.

Este cambio implica agregar un campo adicional en la tabla de novedad_postcontractual que permita tener el enlace de las novedades y leer dese allí todas las novedades asociadas a un documento. Posterior a esto, los documentos fisicos de las novedades se consultaran a través del gestor_documental_mid, mediante el enlace del documento.

**Especificaciones técnicas**

- Actualmente, el último desarrollo asociado se encuentra en la rama develop.
- El cambio en la base de datos en ambiente de pruebas se debe realizar a través de migrate en novedades_crud.

**Sub Tareas**

- [x] Agregar campo "enlace" o "soporte" a la tabla novedad_postcontractual en novedades, a través de migrate.
- [x] Ajustar lógica para que cuando se cree una novedad, se cree primero el documento correspondiente, se obtenga el enlace del mismo y luego se registre toda la data en novedades.
- [x] Ajustar lógica para que cuando se carguen las novedades de un contrato, se lee esa información de la tabla novedad_postcontractual.
- [x] Ajustar lógica para que cuando se carguen las novedades de un contrato y una novedad no cuente con documento fisico, se bloquee la opción de ver documento.

**Criterios de aceptación**

- [x] Cuando se cree una novedad, todos los datos asociados, incluyendo el enlace al documento fisico, debe quedar registrado en la tabla novedad_postcontractual.
- [x] Cuando se carguen las novedades asociadas a un contrato, estas deben ser consultadas directamente de la tabla novedad_postcontractual en novedades.
- [x] Cuando se requiera ver el acta de una novedad, esta debe consultarse al instante mediante el api gestor_documental_mid, con en enlace que esta almacenado en la tabla novedad_postcontractual.

**Requerimientos**

- no presenta.

**Dependencias**

- gestor_documental_mid
- administrativa_amazon_api
- documentos_crud
- parametros_crud
- titan_mid

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Yaov05** [comment]
Commit con los archivos para agregar el campo de enlace del documento en la tabla de novedades a través de migrate: https://github.com/udistrital/novedades_crud/commit/f03a5030b4a510f6f95d89d7575e5fce53f5d702

**Comment by Yaov05** [comment]
Cambios en la lógica al momento de registrar el documento:
https://github.com/udistrital/novedades_cliente/commit/f27d1ad46e10179492597809cae9283ec1f280bc
