### ISSUE TITLE
modificar el cliente para consulta de tipos de novedad

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#49]
(la descripción cambio recientemente a la siguiente)

al culminar la tarea #58 es necesario en el cliente cambiar el servicio de consulta de los tipos de novedades.

antes se consultaban a l api que apunta a la base de datos en mongo, ahora se debe apuntar al api crud de [novedades](https://github.com/udistrital/novedades_crud) creada recientemente.

por lo tanto la se debe cambiar el endpoint al cual se apunta allí.

**Comment by anlramirezs11** [comment]
10/10/2019 
Se reliza un analisis de esta tarea y no se ve necesaria, ya que la forma en que trae los tipos de novedad depende de una logica que está ligada al estado del contrato y además como es un menú que redirige a varias vista se debería implementar la misma logica desde el controlador cosa que se considera inecesaria sabian que ya está implementada en la vista.

![image](https://user-images.githubusercontent.com/29903400/66597663-09ca7c00-eb65-11e9-848a-8e9e9a3e7a6e.png)
