### ISSUE TITLE
Despliegue en producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/novedades_cliente#491]
Se requiere realizar la salida a producción de todas las funcionalidades desarrolladas en Novedades a la fecha, relacionadas con el primer alcance, teniendo en cuenta los siguientes requerimientos:

**Definition of Done - DoD - Despliegues**

- [x] Aprobación Gerente de Proyectos: no obligatorio Hotfix, Bugfix
- [x] Aprobación Funcionamiento
- [x] Actualización de Swagger en WSO2 
- [x] Revisión y actualización de variables de entorno
- [x] Pruebas funcionales (grupo de soporte)
- [x] Pruebas de carga, estrés y seguridad (líder de seguridad)
- [x] Pruebas de usuario (Preguntar Revisión SIGUD)
- [x] Pruebas unitarias (equipo de desarrollo)
- [x] Revisión de sincronización de bases de datos en ambientes (prueba y producción)
- [x] Revisión de estado de bases de datos (ETL)
- [x] Revisión de actualización de APIs consumidas (terceros, transversales)
- [x] Definición y/o actualización de manual de usuario/videotutoriales
- [x] Documento técnico

Los issues relacionados en el despliegue son:
1. #462 
2. #455 
3. #372 
4. #331 
5. #397 
6. #395 
7. #396 
8. #404 
9. #403 
10. #371 
11. #275 
12. #410 
13. #401 
14. #402 
15. #411 
16. #412 
17. #456 
18. #405 
19. #457 
20. #423 
21. #424 
22. #398 
23. #335 
24. #334 
25. #369 
26. #347 
27. #336 
28. #332
29. #329 
30. #333 
31. #288 
32. #316 
33. #315 
34. #327 
35. #313
36.

**Comment by a52290451** [comment]
Para la elaboración del documento técnico, tomar como referencia lo realizado en #398 

Utilizar el siguiente formato:

1. [E-03- Aprobación de entregable Funcionamiento.docx](https://github.com/udistrital/novedades_cliente/files/11437036/E-03-.Aprobacion.de.entregable.Funcionamiento.docx)

**Comment by a52290451** [comment]
Limitaciones:

- Un contrato solo permite realizar una cesión.

Preguntas:

- Se debe consultar cual es el proceso tras realiza una cesión o antes de realizar una cesión con respecto al CDP y vigencia CDP para el contratista que recibe el contrato.

**Comment by a52290451** [comment]
Se realiza solicitud para consulta en SiCapital por número de contrato y vigencia, que devuelva los CDPs, RPs y vigencia asociadas.

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=53340&group_id=133

**Comment by a52290451** [comment]
Se entrega vista para consulta en SiCapital por número de contrato y vigencia, que devuelva los CDPs, RPs y vigencia asociados:

[http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/financiera_produccion/cdprptercerocontrato/{vigencia}/{numero_contrato](http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/financiera_produccion/cdprptercerocontrato/%7Bvigencia%7D/%7Bnumero_contrato)}

Se comprueba su correcto funcionamiento:

![image](https://github.com/udistrital/novedades_cliente/assets/36229498/2e826d27-a5c7-485c-a887-abdcfb3cd744)

**Comment by a52290451** [comment]
Se requiere completar y actualizar manual técnico. El que se encuentra en el link adjunto no esta actualizado.

**Comment by a52290451** [comment]
Pruebas funcionales del sistema en ambiente de pruebas:

#490

**Comment by a52290451** [comment]
Solicitud de actualización de variables de entorno para novedades_mid en ambiente de producción: 

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=53470

**Comment by a52290451** [comment]
Acta de aceptación de entregables #03:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EbQUfI73xJtLhnt9vYNvb2IB2xYapf5dUBs_MrfozYoSQg?e=vEYDIG

Acta de reunión:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EQjhIWdd5qBMofQwaM7F7RoB01MrQ0RuNBxrtQ8XNaC2eA?e=h9lX2J

**Comment by a52290451** [comment]
De acuerdo a reunión con Jurídica, se deben realizar los siguientes ajustes:

https://github.com/udistrital/novedades_cliente/issues/516

**Comment by a52290451** [comment]
Acta de aceptación de entregables #04: 

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EagfjPetwZ5AvwBFCHf55wABmtPv38dPw1nlBl24usl_3w?e=ohwNAM

**Comment by a52290451** [comment]
Se realiza solicitud para actualización de estructura de BD:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=55054&group_id=177

**Comment by a52290451** [comment]
se valida actualización de estructura de BD.

**Comment by milo19980525** [comment]
@Yaov05 con base en el archivo de migración emitido por jurídica, por favor:

1. Filtrar contratos que tengan novedades (Eliminar aquellos que no tengan novedades)
2. Cruzar los contratos que tengan novedades con ARGO y verificar cuales tienen coincidencia.
3. Registrar novedades que no se encontraron en el cruce con Argo. Tener en cuenta todas las condiciones necesarias para registrar la data correctamente).

**Comment by Yaov05** [comment]
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/yaortizv_udistrital_edu_co/EnzOZ2yLVAxLuvEkLxkf2QsByKRZjtBKu0z18aVCAk5Szg?e=WXfKQY

En la carpeta está el archivo reducido de las novedades en formato CSV y el código fuente para ejecutar el script en python. El archivo env_db se debe añadir las credenciales de la bd
