### ISSUE TITLE
Crear los tipos de novedades que seran almacenadas en el api de gobierno.

### ISSUE THREAD

**Issue by BrayanB24** [udistrital/novedades_cliente#51]

**Comment by BrayanB24** [comment]
Se comienza con la ejecución de la tarea.

**Comment by BrayanB24** [comment]
Haciendo un análisis previo el API de parámetros gobierno todavía está en fase de desarrollo por lo que no se ha contemplado todavía una tabla en donde se especifiquen parámetros. Debe consultarse con el equipo correspondiente (core) como debe empezar el proceso, si crear una tabla nueva o esperar al desarrollo.

**Comment by BOTOOM** [comment]
el issue para esta tarea ya existe, el issue es el #48 , por lo tanto 24 horas después de este comentario cerrare este issue, se recomienda pasar comentarios necesarios o información al otro issue
