### ISSUE TITLE
Pruebas funcionales segundo alcance

### ISSUE THREAD

**Issue by milo19980525** [udistrital/novedades_cliente#526]
Se requiere realizar pruebas funcionales del segundo alcance del sistema de novedades; desde la solicitud de novedad contractual hasta aprobación y firma.

Probar todo el flujo por cada una de las novedades posibles.

**Especificaciones técnicas**

- El último desarrollo asociado se encuentra cargado en el repositorio en la rama release/1.0.0, tanto para el cliente como para las APIs mid y crud.

**Sub Tareas**

- [x] Desarrollo de pruebas funcionales de todo el sistema, de acuerdo con el [formato de pruebas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EZkysfyxZZxFkizgi9Uhv2sBlC-g1rG9fAhbLapMJF-d1A?e=e3sUTo) dispuesto.
- [x] Corrección de errores o bugs encontrados, que no requieran gran dedicación para su corrección.
- [x] Listado de bugs o errores encontrados que requieran mayor dedicación para su corrección, con una descripción de su posible solución.

**Criterios de aceptación**

- [x] Todas las funcionalidades del sistema se encuentran probadas.
- [x] Los errores que presenta el sistema se encuentran detectados y listados para su corrección.

**Requerimientos**

- [x] Ninguno.

**Dependencias**

- titan_mid
- administrativa_amazon_api
- gestor_documental_mid
- parametros_crud
- administrativa_mid_api

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas funcionales.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Yaov05** [comment]
Documento con pruebas funcionales segundo alcance:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/yaortizv_udistrital_edu_co/EeYFSC-b2KlJnzBMGCswmkkBUE4A-GQjdklqPnGOASgl1w?e=MUSPj2
