### ISSUE TITLE
Revisión de ejecución de primer alcance en local apuntando a producción todos los endpoints

### ISSUE THREAD

**Issue by milo19980525** [udistrital/novedades_cliente#535]
Se requiere revisar minuciosamente la ejecución del primer alcance de argo en producción.

**Especificaciones técnicas**

- El último despliegue del primer alcance se encuentra en la rama release

**Sub Tareas**

- [x] Revisar todos los endpoints apuntando a ambiente de producción.
- [x] Revisar data que falte por ser añadida en el ambiente de producción (parámetros, gestor documental, etc).
- [x] Verificación del cliente en producción (que responda).
- [x] Realizar scripts de borrado para que Jeisson los ejecute una vez desplegado en producción y probado el primer alcance
- [x] Revisar todo el flujo desde local con todos los endpints de producción.

**Criterios de aceptación**

- [x] Se evidencia en el issue las pruebas realizadas.
- [x] Se documentan los fallos que se presentan o tareas que faltan por hacer.

**Requerimientos**

- [x] Ninguna

**Dependencias**

- administrativa_amazon_api

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Análisis de BDs afectadas cuando se realiza la creación de una novedad:

1. administrativa_amazon_api

- BD: udistrital
- Esquema: argo
- Tablas: novedad_postcontractual, contrato_estado

2. titan_mid -> titan_crud

- BD: udistrital_core
- Esquema: liquidador
- Tabla: novedad

3. novedades_mid -> novedades_crud

- BD: udistrital_administrativa
- Esquema: novedades
- Tablas: novedades_poscontractuales, propiedad, fechas, poliza

4. gestor_documental_mid -> documentos_crud -> nuxeo

- BD: udistrital_core
- Esquema: documento
- Tablas: documento

En el caso de NUXEO, se debe ubicar manualmente los documentos creados y borrarlos por su UID.

**Comment by a52290451** [comment]
Revisión de endpoints y disponibilidad de data en ambiente de producción.

Busqueda de contrato:

- ADMINISTRATIVA_AMAZON_API: http://api.intranetoas.udistrital.edu.co:8104/v1/vigencia_contrato

- ADMINISTRATIVA_AMAZON_API: http://api.intranetoas.udistrital.edu.co:8104/v1/contrato_general/?query=ContratoSuscrito.NumeroContratoSuscrito:785,VigenciaContrato:2022

- ADMINISTRATIVA_AMAZON_API:  http://api.intranetoas.udistrital.edu.co:8104/v1/contrato_estado/?query=NumeroContrato:10386,Vigencia:2022&sortby=Id&order=desc&limit=1

- NOVEDADES_MID: http://api.intranetoas.udistrital.edu.co:8502/v1/novedad/785/2022

- [INTERNO] NOVEDADES_CRUD: http://api.intranetoas.udistrital.edu.co:8501/v1/novedades_poscontractuales/?query=contrato_id:785,vigencia:2022&limit=0&sortby=FechaCreacion&order=asc

- [INTERNO] NOVEDADES_CRUD: http://api.intranetoas.udistrital.edu.co:8501/v1/fechas/?query=id_novedades_poscontractuales:2181&limit=0

- [INTERNO] NOVEDADES_CRUD: http://api.intranetoas.udistrital.edu.co:8501/v1/propiedad/?query=id_novedades_poscontractuales:2181&limit=0

- [INTERNO] NOVEDADES_CRUD: http://api.intranetoas.udistrital.edu.co:8501/v1/tipo_novedad/?query=Id:8&limit=0

- [INTERNO] PARAMETROS_CRUD: http://api.intranetoas.udistrital.edu.co:8510/v1/parametro/4518

**Nota: ** Se requiere actualizar información de parámetros para novedades en producción. (Correr Script)

-

**Comment by a52290451** [comment]
Correcciones requeridas:

- Se requiere Ajustar consulta a parámetros, cambiado el ID por el código de abreviación. De esta forma se evitan discrepancias entre ambiente de pruebas y de producción.
- Se requiere correr script en producción para agregar parámetros asociados a novedades.

**Comment by Yaov05** [comment]
Script para agregar parámetros:

https://udistritaleduco-my.sharepoint.com/:f:/g/personal/yaortizv_udistrital_edu_co/EipxowaMBaFHikYKQUEhussBsia4v5edTZk_v42CXpknKg?e=CnrKiK

Es necesario ejecutar primero la sentencia del archivo "script_tipo_parametro.sql", para poder utilizar el id de ese registro en el último campo de la sentencia del archivo "script_parametros_primer_alcance.sql" (tipo_parametro_id).

**Comment by a52290451** [comment]
Se comprueba funcionamiento de servicio "upload" del API "gestor_documental_mid" en ambiente de producción

![image](https://github.com/udistrital/novedades_cliente/assets/36229498/1e341e66-7363-4db6-8755-c9b87da49cca)

Se comprueba funcionamiento de consulta de documentos del API "gestor_documental_mid" en ambiente de producción

![image](https://github.com/udistrital/novedades_cliente/assets/36229498/30c5f644-d73d-4c88-9ac3-8972246bb8ae)

**Comment by a52290451** [comment]
Queda pendiente subir a producción el API_MID, CRUD y el CLIENTE.

**Comment by Yaov05** [comment]
Script para borrado de data de las tablas de novedades:
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/yaortizv_udistrital_edu_co/Eil-aF7s_JtDrjZkDbOceboBwc2mdgPF4Fj0aU7YJKJtbw?e=BXuKPB

**Comment by milo19980525** [comment]
Faltan los scripts de borrado de las tablas de replica.

**Comment by Yaov05** [comment]
Script para el borrado de las tablas de datos replicados de novedades:
https://udistritaleduco-my.sharepoint.com/:f:/g/personal/yaortizv_udistrital_edu_co/Eu1f2OFmK9hEohQuqB1g108B-aJrfJG6AfnHaxqRbNrXaA?e=S8TdjN

Se tendrían dos métodos para el borrado de data de la réplica:

- Los archivos con el nombre script_borrado_data_replica_argo y script_borrado_data_replica_titan se deberían ejectutar manualmente luego de tener las novedades registradas.

- El archivo script_borrado_data_replica_dblink utiliza la extensión dblink de postgresql para conectarse a la base de datos donde se registran las novedades y eliminar datos teniendo en cuenta valores como el número de contrato y la vigencia, por lo que borraría los datos de todas las novedades de un contrato.
