### ISSUE TITLE
Correcciones finales Primer Alcance

### ISSUE THREAD

**Issue by milo19980525** [udistrital/novedades_cliente#559]
Se requiere realizar ajustes o correcciones necesarias en el primer alcance para salir a producción .

**Especificaciones técnicas**

- El último despliegue del primer alcance se encuentra en la rama master.
- Se debe realizar un hotfix sobre master.

**Sub Tareas**

- [x] Eliminar petición de consulta de CDP's por contrato, dejar campo manual (no se puede traer un listado de CDPs relacionados a un contrato).
- [x] En la novedad de **cesión** eliminar el número de solicitud dado que no se refleja en la rúbrica.
- [x] En la novedad de **terminación anticipada** en el punto 7 quitar número certificado y permitir que en se ingrese la fecha del certificado y añadirla al comienzo del punto 7.
- [x] En **todas** las novedades añadir un campo de "fecha de expedición" y que se refleje al final de todas las actas previo a la firma. Lo anterior para que ya no se ingrese manualmente.
- [x] Cambiar en las plantillas e interfaz gráfica todo lo relacionado con:

- Oficina Asesora Jurídica a Oficina de Contratación
- OAJ a OC
- Sección de Presupuesto por Unidad de Presupuesto.

**Criterios de aceptación**

- [x] Se documentan correcciones realizadas y prueba de funcionamiento.

**Requerimientos**

- [x] ninguno

**Dependencias**

- administrativa_amazon_api

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Master.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Yaov05** [comment]
En todas las novedades (exceptuando adición/prórroga), se cambia el campo de número de solicitud por fecha de expedición del acta, que se verá reflejada en el acta.

![image](https://github.com/udistrital/novedades_cliente/assets/42217637/091e1279-d7b0-4405-82b0-085d21f9f0b7)

![image](https://github.com/udistrital/novedades_cliente/assets/42217637/6f5f56cc-5f50-430b-b8d1-3b2132c944d2)

**Comment by Yaov05** [comment]
![image](https://github.com/udistrital/novedades_cliente/assets/42217637/2778424e-e925-4a82-baa7-f756f9977ec1)

**Comment by Yaov05** [comment]
Campo de CDP para otro sí:
![image](https://github.com/udistrital/novedades_cliente/assets/42217637/75a5f182-109b-458c-a417-464afa639746)

**Comment by milo19980525** [comment]
@Yaov05 porfa mandar cambios a pruebas, probar y a producción.
