### ISSUE TITLE
crear tipos de novedades a ingresar en el modelo de datos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#58]
se necesita crear una lista (en hoja de calculo de drive) en la cual estén listados los tipos de novedades que usa el negocio de novedades.

Esto para el modelo de datos del issue #41 

se procede a realizar esta acción junto a la de agregar la tabla de novedades al modelo del issue #41 debido a los acontecimientos mencionados en el issue #47

**Comment by BrayanB24** [comment]
Con base en la información que se tiene en la base de MongoDB para los tipos de novedades postcontractuales, se propone la tabla con los datos correspondientes en un documento de hoja de cálculo de google drive el cual se encuentra en el siguiente link: 

[https://docs.google.com/spreadsheets/d/11A7x3eZb5A9wqksef8NWBLslt8k6K5-ItbdWXu7htM8/edit?usp=sharing](url)

También se deja su propuesta en imágen aquí:

![image](https://user-images.githubusercontent.com/45292226/65777345-7aa37a00-e109-11e9-9073-5e38d486ee76.png)

Se queda pendiente a la aprobación del lider técnico @BOTOOM de la propuesta de la información contenida en esta tabla.

**Comment by BOTOOM** [comment]
se realizaran observaciones en orden según los campos en la tabla:

- el id esta bien que este vació ya que es un autonumerico.
- el campo nombre esta bien, no requiere mas información allí.
- las descripciones de las novedades están bien, solo espero que no pase los 250 caracteres ya que según lineamiento eso es lo máximo que puede tener ese campo( por fa revisa ese pequeño dato).
- para el código de abreviación no me parecen, ya que el código deberia de referencia de forma corta el tipo de novedad y `NP001`, sinceramente no me dice nada, yo propondría un ejemplo para novedad de suspensión : `NP_SUS` o algo similar.
- en activo deberían de estar todos en `true`

los demás datos pueden ir en vació ya por que el modelo lo permite o porque se crearan al momento de crear el registro en base de datos

**Comment by BrayanB24** [comment]
Se realizan las modificaciones dichas por el lider técnico del proyecto @BOTOOM y se hace la nueva propuesta de los datos de la tabla en el mismo documento antes compartido: 

![image](https://user-images.githubusercontent.com/45292226/65891533-509cc280-e36a-11e9-9dff-96f35a9cbf20.png)
