### ISSUE TITLE
Ajustar acta de novedad de cesiòn

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#6]
Al realizarse la cesión de un contrato y querer ver el nuevo contrato se ven datos del contrato anterior o datos erróneos.

***objetivos***
- [ ] el numero de póliza debe cambiar al realizar la cesión.
- [ ] los meses de duración del contrato deben de ser re calculados u obtenidos.
- [x] el tomador del contrato debe ser cambiado después de realizar la cesión.
- [ ] el valor del contrato debe ser re calculado u obtenido según la novedad.

***Calidad (esta verificación debe ser presenciada por un integrante del equipo)***
verificar al realizar la cesión de contrato 

- [ ] validar que el numero de póliza cambia al efectuar la cesión.
- [ ] verificar que los meses han sido re-calculados correctamente después de haberse efectuado la cesión.
- [ ] validar que la persona que es tomador de contrato cambia al realizar la cesión.
- [ ] verificar que el valor del contrato ha sido re-calculados u obtenido correctamente después de haberse efectuado la cesión.

**Comment by anlramirezs11** [comment]
Se logra atrer correctamente los datos del nuevo contratista: 
![Screenshot from 2019-06-20 16-19-29](https://user-images.githubusercontent.com/29903400/59882488-f8702080-9377-11e9-8bd5-0f3f1c2206ea.png)

Falta generar el pdf con los nuevos datos, ya que se genera error al generarse.

**Comment by anlramirezs11** [comment]
Ya se genera el pdf de la acta de inicio de cesión: 
![Screenshot from 2019-06-25 14-55-51](https://user-images.githubusercontent.com/29903400/60128869-4bbbe780-9759-11e9-9abe-47661fe6b9e9.png)


Falta determinar que hacer con el plazo y el monto del contrato. Y hacer que el hacer que siga a la siguiente etapa.

**Comment by BOTOOM** [comment]
se estiman 13 horas

**Comment by BOTOOM** [comment]
se cierra ya que ya se maneja en los siguientes issues #72 #68 #69
