### ISSUE TITLE
Modificación general del cliente de novedades

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#68]
debido a que este cliente ya no consume el api de go para la base de datos mongo y en su lugar ahora se usan 2 apis (crud y mid) las cuales llevan a una base de datos de postgres., se requieren realizar varios ajustes.

- [x] revisar la estructura de los json que se envian hacia el api y documentarlos ya que estos se enviaran al mid. 

- [x] ajustar en el archivo de configuración el path para la comunicación con el mid y el crud. 

- [x] ya que antes solo se apuntaba a un api para novedades y ahora son 2 se debe realizar lo siguiente:

    - [x] crear un archivo de servicio extra para poder realizar consultas ( se recomienda que sea para el crud ya que es el que menos se usara) 
 
     - [x] para el archivo de servicio nuevo se debe de llamar en el archivo donde se hace la consulta de tipos de novedades para poder consultar el servicio. 

    - [x] realizar los imports y modificaciones necesarias para que los servicios de crud y mid puedan ser consumidos.

- [x] en comunicación con él o los desarrolladores de las apis ajustar los endpoint para envió de información.

**Comment by anlramirezs11** [comment]
7/10/2019
* Se procede a hacer correr el proyecto en local. 
* Se crea el menú para novedades.
![image](https://user-images.githubusercontent.com/29903400/66330224-93741280-e8f5-11e9-93f0-5e65d938fb82.png)

**Comment by anlramirezs11** [comment]
8/10/2019
Todas las peticines post que aqué se hacen apuntan a: 
 https://autenticacion.portaloas.udistrital.edu.co/apioas/novedades_crud/v1/

* Novedad de Adición Json: 
`{
"contrato":"1178",
"numerosolicitud":117802,
"fechasolicitud":"2019-10-08T15:07:48.606Z",
"numerocdp":"55",
"valoradicion":2000000,
"fechaadicion":"2019-10-08T15:08:32.972Z",
"vigencia":"2019",
"motivo":"Prueba 2 de Adiccion",
"tiponovedad":"59d7985e867ee188e42d8e64",
"cesionario":12272
}`

**Comment by anlramirezs11** [comment]
9/10/2019

* Se edita el acta inicio y trae los datos que corresponden.

* Se edita de acta adcion y prorroga solo falt aun dato que se obtine haciendo esta peticion: http://pruebasapi.intranetoas.udistrital.edu.co:8104/v1/contrato_disponibilidad?query=NumeroContrato:1178&VigenciaCdp:2019 
El problema es que la petición no devuelve los datos reales asociados a esta query.

**Comment by anlramirezs11** [comment]
11/10/2019
* Se realiza la conexión con novedades_crud para traer el codigo de abreviación de los tipos de novedades y reemplazarlo por id alfaumerico que estaba enviando. Solo se ha implementado en Adición y Prorroga.

**Comment by BOTOOM** [comment]
ya que según requerimiento que se realizaron con anterioridad en los cuales para el modelo de datos se pidió que al guardar la póliza se guardara la entidad aseguradora de la póliza (requerimiento dado por el equipo de soporte y aprobado por arquitectos). se plantearon varias formas para buscar y obtener estos datos, la manera mas factible de realizarlo es desde el cliente, por ende se debe de realizar lo siguiente:

- en las secciones donde se ingrese una poliza se ede habilitar un select en el cual se listen los diferentes tipos de entidad aseguradora y seleccionar uno para acociarlo a la poliza.
- los datos de la entidad aseguradora se deben de buscar en el api del core (core crud).----- (he buscado en que api se puede consumir el dato y no lo he encontrado apenas lo encuentre acutalizare el comentario).
- mientras se consigue dicha información para dejar listo el link de para esto, dejar un select con datos dummy u mandarle ese id extra en un json(para el json comunicarse con el desarrollador del mid ).
