### ISSUE TITLE
Cambiar nombre de pdfs para agregar el número del contrato.

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#8]
Cambiar el nombre con el cual se descarga el pdf generado de la novedad.

Esto con el fin de que al descargarse el archivo se sepa que tipo de novedad es y a que contrato pertenece

formato sugerigerido: 
-`acta_[tipo de novedad]_contrato_[numero del contrato].pdf` (formato corregido gracias a un comentario en el issue)

**Comment by anlramirezs11** [comment]
El formato que se propuso es: 
acta_[tipo de novedad]_contrato_[numero del contrato].pdf

**Comment by BOTOOM** [comment]
tarea finalizada y se procede a cerrar el presente issue
