### ISSUE TITLE
Realizar pruebas de generación de pdf

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#9]
con el fin de verificar y validar el funcionamiento correcto al generar el pdf de las novedades cada miembro del equipo debe realizar pruebas de ello y en el presente issue describir el estado de sus pruebas sean fallidas o exitosas.

**Comment by BOTOOM** [comment]
se estiman 5 horas

**Comment by anlramirezs11** [comment]
@BOTOOM  @BrayanB24  Se están relizando pruebas de terminación de contrato sobre los contratos del 0 al 100

**Comment by anlramirezs11** [comment]
Se relizan pruebas de la novedad "Terminación Anticipada" de los contratos del 1 al 120; se encuentra lo que generaba el error y se corrige.

**Comment by BOTOOM** [comment]
se han realizado algunas pruebas de generación de pdf , se ha encontrado un error en el código y se ha corregido.
