### ISSUE TITLE
Agregar funcionalidad para añadir poliza e un contrato cedido.

### ISSUE THREAD

**Issue by anlramirezs11** [udistrital/novedades_cliente#96]
El ususario deberá ingresar la poliza del contrato para habilitar las novedades.

**Comment by anlramirezs11** [comment]
Al ingresar a un contrato que fue cedido el sistema mostrará el siguiente mensaje y habilitará la opción de agregar poliza.
![image](https://user-images.githubusercontent.com/29903400/69274531-8743cc00-0ba8-11ea-9d5b-f7f691510c22.png)

![image](https://user-images.githubusercontent.com/29903400/69274609-b5c1a700-0ba8-11ea-9adf-0760cbb5c752.png)

**Comment by BOTOOM** [comment]
para terminar la función de añadir la póliza hace falta poder obtener un servicio para recibir las entidad es aseguradoras, dicho servicio ya fue construido pero en su despliegue no se detecta el ednpoint, por ende esta tarea queda suspendida hasta que se resuelva ese error

**Comment by anlramirezs11** [comment]
Todo ok!!
