### ISSUE TITLE
listar datos que recibe el cliente de novedades

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/novedades_cliente#97]
Con el fin de conseguir la funcionalidad optima del modulo de novedades se procederán a realizar varios ajustes que implican al cliente y a mid de novedades, por ende gran parte de la lógica que hace el cliente sera enviada al mid(esto debió ser así desde un inicio por buenas practicas).

para la primera parte de este ajuste es necesario saber que datos pide el mid de los contratos y como los usa, así mismo para las novedades, ya que estos serán solicitados, procesados y enviados por el mid.

**Comment by anlramirezs11** [comment]
Lista de datos que se que se consultan en el cliente para pasarlos al mid: https://docs.google.com/spreadsheets/d/1K3ckeuoggz5M7P-HhkU-utLllibNsdwc43RGwCt-Ut8/edit#gid=0
